"""Package 1 customer, tenant, commercial, provisioning and health foundation."""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = "ad46customertenant"
down_revision = ("aa43durablemfa", "ac45compliancecontrols")
branch_labels = None
depends_on = None

UUID = postgresql.UUID(as_uuid=True)
JSONB = postgresql.JSONB()
TS = sa.DateTime(timezone=True)


def _id(): return sa.Column("id", UUID, primary_key=True, server_default=sa.text("gen_random_uuid()"))
def _tenant(nullable=False): return sa.Column("tenant_id", UUID, sa.ForeignKey("tenants.id"), nullable=nullable)
def _created(): return sa.Column("created_at", TS, nullable=False, server_default=sa.text("now()"))
def _updated(): return sa.Column("updated_at", TS, nullable=False, server_default=sa.text("now()"))


def upgrade():
    op.create_table("customers", _id(), sa.Column("customer_identifier", sa.String(40), nullable=False), sa.Column("legal_name", sa.String(255), nullable=False), sa.Column("display_name", sa.String(255), nullable=False), sa.Column("trading_name", sa.String(255)), sa.Column("customer_type", sa.String(80), nullable=False), sa.Column("industry", sa.String(120)), sa.Column("company_size", sa.String(80)), sa.Column("country", sa.String(80), nullable=False), sa.Column("state_province", sa.String(120)), sa.Column("headquarters", sa.String(255)), sa.Column("website", sa.String(500)), sa.Column("crm_reference", sa.String(160)), sa.Column("primary_business_contact", JSONB), sa.Column("billing_contact", JSONB), sa.Column("internal_account_owner", sa.String(160)), sa.Column("implementation_manager", sa.String(160)), sa.Column("lifecycle_status", sa.String(40), nullable=False, server_default="DRAFT"), sa.Column("lock_version", sa.Integer(), nullable=False, server_default="1"), sa.Column("created_by", UUID), sa.Column("updated_by", UUID), _created(), _updated(), sa.UniqueConstraint("customer_identifier", name="uq_customers_customer_identifier"), sa.CheckConstraint("lifecycle_status in ('DRAFT','PENDING_APPROVAL','PROVISIONING','PROVISIONED','PENDING_CUSTOMER_ACTIVATION','ACTIVE','EXPIRING_SOON','EXPIRED','SUSPENDED','TERMINATED','ARCHIVED')", name="customer_lifecycle_status_allowed"))
    op.create_index("ix_customers_directory", "customers", ["lifecycle_status", "country", "display_name"])

    # Preserve every legacy tenant by creating one parent customer before making the FK mandatory.
    for name, typ in (("customer_id", UUID), ("tenant_identifier", sa.String(100)), ("display_name", sa.String(255)), ("tenant_slug", sa.String(120)), ("tenant_type", sa.String(40)), ("deployment_model", sa.String(60)), ("primary_region", sa.String(80)), ("residency_region", sa.String(80)), ("database_region", sa.String(80)), ("backup_region", sa.String(80)), ("storage_region", sa.String(80)), ("ai_processing_region", sa.String(80)), ("disaster_recovery_region", sa.String(80)), ("cross_border_processing_allowed", sa.Boolean()), ("application_version", sa.String(80)), ("schema_version", sa.String(80)), ("configuration_version", sa.String(80)), ("provisioning_status", sa.String(40)), ("activated_at", TS), ("suspended_at", TS), ("terminated_at", TS), ("lock_version", sa.Integer())):
        op.add_column("tenants", sa.Column(name, typ, nullable=True))
    op.execute("""INSERT INTO customers (id, customer_identifier, legal_name, display_name, customer_type, country, lifecycle_status, lock_version, crm_reference, created_at, updated_at)
      SELECT gen_random_uuid(), 'CUST-' || upper(substr(replace(id::text,'-',''),1,12)), name, name, 'LEGACY', 'UNSPECIFIED', 'ACTIVE', 1, 'LEGACY-TENANT:' || id::text, created_at, updated_at FROM tenants""")
    op.execute("""UPDATE tenants t SET customer_id=c.id, tenant_identifier=t.tenant_key, display_name=t.name, tenant_slug=lower(regexp_replace(t.tenant_key,'[^a-zA-Z0-9]+','-','g')), tenant_type='STANDARD', deployment_model='SHARED', primary_region='UNSPECIFIED', residency_region='UNSPECIFIED', cross_border_processing_allowed=false, provisioning_status='PROVISIONED', status=upper(t.status), lock_version=1, activated_at=CASE WHEN upper(t.status)='ACTIVE' THEN t.updated_at END FROM customers c WHERE c.crm_reference='LEGACY-TENANT:' || t.id::text""")
    for name in ("customer_id","tenant_identifier","display_name","tenant_slug","tenant_type","deployment_model","primary_region","residency_region","cross_border_processing_allowed","provisioning_status","lock_version"):
        op.alter_column("tenants", name, nullable=False)
    op.create_foreign_key("fk_tenants_customer_id_customers", "tenants", "customers", ["customer_id"], ["id"])
    op.create_unique_constraint("uq_tenants_tenant_identifier", "tenants", ["tenant_identifier"]); op.create_unique_constraint("uq_tenants_tenant_slug", "tenants", ["tenant_slug"]); op.create_unique_constraint("uq_tenants_customer_id_id", "tenants", ["customer_id","id"])
    op.create_check_constraint("tenant_lifecycle_status_allowed", "tenants", "status in ('DRAFT','PENDING_APPROVAL','PROVISIONING','PROVISIONED','PENDING_CUSTOMER_ACTIVATION','ACTIVE','EXPIRING_SOON','EXPIRED','SUSPENDED','TERMINATED','ARCHIVED')")
    op.create_check_constraint("tenant_provisioning_status_allowed", "tenants", "provisioning_status in ('DRAFT','QUEUED','RUNNING','FAILED','PROVISIONED','ACTIVE')")
    op.create_check_constraint("tenant_type_allowed", "tenants", "tenant_type in ('STANDARD','ENTERPRISE','PRIVATE_DEPLOYMENT')")
    op.create_index("ix_tenants_customer_status_region", "tenants", ["customer_id","status","primary_region"])

    op.create_table("tenant_environments", _id(), _tenant(), sa.Column("environment_identifier", sa.String(120), nullable=False), sa.Column("environment_type", sa.String(30), nullable=False), sa.Column("region", sa.String(80), nullable=False), sa.Column("residency_region", sa.String(80), nullable=False), sa.Column("application_version", sa.String(80)), sa.Column("schema_version", sa.String(80)), sa.Column("configuration_version", sa.String(80)), sa.Column("status", sa.String(30), nullable=False, server_default="DRAFT"), sa.Column("provisioned_at", TS), sa.Column("activated_at", TS), sa.Column("clone_source_environment_id", UUID), _created(), _updated(), sa.ForeignKeyConstraint(["tenant_id","clone_source_environment_id"],["tenant_environments.tenant_id","tenant_environments.id"]), sa.UniqueConstraint("tenant_id","environment_identifier",name="uq_tenant_environment_identifier"), sa.UniqueConstraint("tenant_id","environment_type",name="uq_tenant_environment_type"), sa.UniqueConstraint("tenant_id","id",name="uq_tenant_environment_tenant_id"), sa.CheckConstraint("environment_type in ('PRODUCTION','SANDBOX','VALIDATION','UAT','DEMO')",name="tenant_environment_type_allowed"), sa.CheckConstraint("status in ('DRAFT','PROVISIONING','ACTIVE','SUSPENDED','ARCHIVED','FAILED')",name="tenant_environment_status_allowed"))
    op.create_index("ix_tenant_environments_status", "tenant_environments", ["tenant_id","status","environment_type"])

    op.create_table("customer_contacts", _id(), sa.Column("customer_id",UUID,sa.ForeignKey("customers.id"),nullable=False), sa.Column("contact_type",sa.String(40),nullable=False), sa.Column("name",sa.String(160),nullable=False), sa.Column("email",sa.String(254),nullable=False), sa.Column("phone",sa.String(60)), sa.Column("status",sa.String(30),nullable=False,server_default="ACTIVE"), _created(), _updated(), sa.UniqueConstraint("customer_id","contact_type","email",name="uq_customer_contact_type_email"))
    op.create_table("customer_domains", _id(), sa.Column("customer_id",UUID,sa.ForeignKey("customers.id"),nullable=False), sa.Column("domain",sa.String(255),nullable=False), sa.Column("status",sa.String(30),nullable=False,server_default="PENDING"), _created(), _updated(), sa.UniqueConstraint("customer_id","domain",name="uq_customer_domain"))
    op.create_table("domain_verifications", _id(), sa.Column("customer_domain_id",UUID,sa.ForeignKey("customer_domains.id"),nullable=False), sa.Column("verification_method",sa.String(40),nullable=False), sa.Column("verification_token_hash",sa.String(128)), sa.Column("status",sa.String(30),nullable=False,server_default="PENDING"), sa.Column("verified_at",TS), sa.Column("expires_at",TS), _created())
    op.create_table("identity_provider_configurations", _id(), _tenant(), sa.Column("provider_type",sa.String(40),nullable=False), sa.Column("issuer",sa.String(500)), sa.Column("client_reference",sa.String(255)), sa.Column("login_mode",sa.String(30),nullable=False,server_default="PASSWORD_MFA"), sa.Column("configuration",JSONB,nullable=False,server_default="{}"), sa.Column("status",sa.String(30),nullable=False,server_default="PENDING"), sa.Column("verified_at",TS), _created(), _updated(), sa.UniqueConstraint("tenant_id","provider_type",name="uq_tenant_identity_provider"), sa.UniqueConstraint("tenant_id","id",name="uq_identity_provider_tenant_id"))
    op.create_table("support_access_grants", _id(), _tenant(), sa.Column("platform_user_id",UUID,nullable=False), sa.Column("scope",JSONB,nullable=False), sa.Column("reason",sa.Text(),nullable=False), sa.Column("status",sa.String(30),nullable=False,server_default="PENDING"), sa.Column("approved_by",UUID), sa.Column("starts_at",TS,nullable=False), sa.Column("expires_at",TS,nullable=False), sa.Column("revoked_at",TS), _created(), _updated(), sa.UniqueConstraint("tenant_id","id",name="uq_support_access_grant_tenant_id"), sa.CheckConstraint("expires_at > starts_at",name="support_access_expiry_after_start"))

    op.create_unique_constraint("uq_subscription_reminder_policy_tenant_id", "subscription_reminder_policies", ["tenant_id","id"])
    op.create_table("subscription_versions", _id(), _tenant(), sa.Column("subscription_id",UUID,nullable=False), sa.Column("version",sa.Integer(),nullable=False), sa.Column("snapshot",JSONB,nullable=False), sa.Column("reason",sa.Text(),nullable=False), sa.Column("created_by",UUID), _created(), sa.ForeignKeyConstraint(["tenant_id","subscription_id"],["subscription_lifecycles.tenant_id","subscription_lifecycles.id"]), sa.UniqueConstraint("tenant_id","subscription_id","version",name="uq_subscription_version"), sa.UniqueConstraint("tenant_id","id",name="uq_subscription_version_tenant_id"))
    op.create_table("license_transitions", _id(), _tenant(), sa.Column("subscription_id",UUID,nullable=False), sa.Column("from_status",sa.String(40)), sa.Column("to_status",sa.String(40),nullable=False), sa.Column("reason",sa.Text(),nullable=False), sa.Column("effective_at",TS,nullable=False), sa.Column("created_by",UUID), _created(), sa.ForeignKeyConstraint(["tenant_id","subscription_id"],["subscription_lifecycles.tenant_id","subscription_lifecycles.id"]), sa.UniqueConstraint("tenant_id","id",name="uq_license_transition_tenant_id"))
    op.create_table("grace_period_exceptions", _id(), _tenant(), sa.Column("subscription_id",UUID,nullable=False), sa.Column("starts_at",TS,nullable=False), sa.Column("expires_at",TS,nullable=False), sa.Column("reason",sa.Text(),nullable=False), sa.Column("approved_by",UUID,nullable=False), sa.Column("status",sa.String(30),nullable=False,server_default="ACTIVE"), _created(), sa.ForeignKeyConstraint(["tenant_id","subscription_id"],["subscription_lifecycles.tenant_id","subscription_lifecycles.id"]), sa.CheckConstraint("expires_at > starts_at",name="grace_exception_expiry_after_start"), sa.UniqueConstraint("tenant_id","id",name="uq_grace_period_exception_tenant_id"))
    op.create_table("plan_version_assignments", _id(), _tenant(), sa.Column("plan_id",UUID,sa.ForeignKey("plan_definitions.id"),nullable=False), sa.Column("plan_version",sa.String(40),nullable=False), sa.Column("effective_from",TS,nullable=False), sa.Column("effective_to",TS), sa.Column("status",sa.String(30),nullable=False,server_default="ACTIVE"), _created(), _updated(), sa.UniqueConstraint("tenant_id","plan_id","plan_version",name="uq_plan_version_assignment"), sa.UniqueConstraint("tenant_id","id",name="uq_plan_version_assignment_tenant_id"))
    op.create_table("entitlement_snapshots", _id(), _tenant(), sa.Column("plan_version_assignment_id",UUID,nullable=False), sa.Column("version",sa.String(40),nullable=False), sa.Column("entitlements",JSONB,nullable=False), sa.Column("effective_at",TS,nullable=False), _created(), sa.ForeignKeyConstraint(["tenant_id","plan_version_assignment_id"],["plan_version_assignments.tenant_id","plan_version_assignments.id"]), sa.UniqueConstraint("tenant_id","version",name="uq_entitlement_snapshot_version"), sa.UniqueConstraint("tenant_id","id",name="uq_entitlement_snapshot_tenant_id"))
    op.create_table("usage_quota_snapshots", _id(), _tenant(), sa.Column("captured_at",TS,nullable=False), sa.Column("active_users",sa.Integer(),nullable=False,server_default="0"), sa.Column("storage_bytes",sa.BigInteger(),nullable=False,server_default="0"), sa.Column("api_requests",sa.BigInteger(),nullable=False,server_default="0"), sa.Column("ai_tokens",sa.BigInteger(),nullable=False,server_default="0"), sa.Column("quota",JSONB,nullable=False,server_default="{}"), _created(), sa.UniqueConstraint("tenant_id","captured_at",name="uq_usage_quota_snapshot_time"), sa.UniqueConstraint("tenant_id","id",name="uq_usage_quota_snapshot_tenant_id"))
    op.create_table("renewal_requests", _id(), _tenant(), sa.Column("subscription_id",UUID,nullable=False), sa.Column("requested_by",UUID,nullable=False), sa.Column("request_details",JSONB,nullable=False,server_default="{}"), sa.Column("status",sa.String(30),nullable=False,server_default="REQUESTED"), sa.Column("resolved_at",TS), _created(), _updated(), sa.ForeignKeyConstraint(["tenant_id","subscription_id"],["subscription_lifecycles.tenant_id","subscription_lifecycles.id"]), sa.UniqueConstraint("tenant_id","id",name="uq_renewal_request_tenant_id"))
    op.create_table("reminder_policy_recipients", _id(), _tenant(), sa.Column("reminder_policy_id",UUID,nullable=False), sa.Column("recipient_type",sa.String(60),nullable=False), sa.Column("contact_id",UUID,sa.ForeignKey("customer_contacts.id")), sa.Column("status",sa.String(30),nullable=False,server_default="ACTIVE"), _created(), sa.ForeignKeyConstraint(["tenant_id","reminder_policy_id"],["subscription_reminder_policies.tenant_id","subscription_reminder_policies.id"]), sa.UniqueConstraint("tenant_id","reminder_policy_id","recipient_type","contact_id",name="uq_reminder_policy_recipient"), sa.UniqueConstraint("tenant_id","id",name="uq_reminder_policy_recipient_tenant_id"))
    op.create_index("ix_subscription_lifecycles_expiry", "subscription_lifecycles", ["status","expires_at"])

    op.create_table("customer_onboarding_drafts", _id(), sa.Column("customer_id",UUID,sa.ForeignKey("customers.id")), sa.Column("idempotency_key",sa.String(160),nullable=False,unique=True), sa.Column("current_step",sa.Integer(),nullable=False,server_default="1"), sa.Column("draft_data",JSONB,nullable=False,server_default="{}"), sa.Column("status",sa.String(30),nullable=False,server_default="DRAFT"), sa.Column("failure_details",JSONB), sa.Column("retry_count",sa.Integer(),nullable=False,server_default="0"), sa.Column("created_by",UUID,nullable=False), _created(), _updated())
    op.create_table("provisioning_jobs", _id(), sa.Column("customer_id",UUID,sa.ForeignKey("customers.id"),nullable=False), _tenant(True), sa.Column("job_identifier",sa.String(60),nullable=False,unique=True), sa.Column("idempotency_key",sa.String(160),nullable=False,unique=True), sa.Column("status",sa.String(30),nullable=False,server_default="QUEUED"), sa.Column("failure_details",JSONB), sa.Column("retry_count",sa.Integer(),nullable=False,server_default="0"), sa.Column("started_at",TS), sa.Column("completed_at",TS), _created(), _updated())
    op.create_table("provisioning_job_steps", _id(), sa.Column("provisioning_job_id",UUID,sa.ForeignKey("provisioning_jobs.id"),nullable=False), _tenant(True), sa.Column("step_code",sa.String(80),nullable=False), sa.Column("sequence",sa.Integer(),nullable=False), sa.Column("status",sa.String(30),nullable=False,server_default="PENDING"), sa.Column("attempt_count",sa.Integer(),nullable=False,server_default="0"), sa.Column("failure_details",JSONB), sa.Column("started_at",TS), sa.Column("completed_at",TS), _created(), _updated(), sa.UniqueConstraint("provisioning_job_id","step_code",name="uq_provisioning_job_step"))
    op.create_index("ix_provisioning_jobs_status", "provisioning_jobs", ["status","created_at"])

    op.create_table("configuration_baselines", _id(), sa.Column("code",sa.String(100),nullable=False,unique=True), sa.Column("name",sa.String(160),nullable=False), sa.Column("status",sa.String(30),nullable=False,server_default="ACTIVE"), _created(), _updated())
    op.create_table("configuration_baseline_versions", _id(), sa.Column("baseline_id",UUID,sa.ForeignKey("configuration_baselines.id"),nullable=False), sa.Column("version",sa.String(40),nullable=False), sa.Column("definition",JSONB,nullable=False), sa.Column("status",sa.String(30),nullable=False,server_default="DRAFT"), sa.Column("released_at",TS), _created(), _updated(), sa.UniqueConstraint("baseline_id","version",name="uq_configuration_baseline_version"))
    op.create_table("tenant_baseline_adoptions", _id(), _tenant(), sa.Column("baseline_version_id",UUID,sa.ForeignKey("configuration_baseline_versions.id"),nullable=False), sa.Column("status",sa.String(30),nullable=False,server_default="PENDING_REVIEW"), sa.Column("adopted_at",TS), sa.Column("deferred_until",TS), _created(), _updated(), sa.UniqueConstraint("tenant_id","baseline_version_id",name="uq_tenant_baseline_adoption"), sa.UniqueConstraint("tenant_id","id",name="uq_tenant_baseline_adoption_tenant_id"))
    op.create_table("baseline_differences", _id(), sa.Column("from_version_id",UUID,sa.ForeignKey("configuration_baseline_versions.id"),nullable=False), sa.Column("to_version_id",UUID,sa.ForeignKey("configuration_baseline_versions.id"),nullable=False), sa.Column("differences",JSONB,nullable=False), _created(), sa.UniqueConstraint("from_version_id","to_version_id",name="uq_baseline_difference_versions"))
    op.create_table("baseline_adoption_decisions", _id(), _tenant(), sa.Column("adoption_id",UUID,nullable=False), sa.Column("decision",sa.String(30),nullable=False), sa.Column("selected_changes",JSONB,nullable=False,server_default="{}"), sa.Column("reason",sa.Text(),nullable=False), sa.Column("decided_by",UUID,nullable=False), sa.Column("decided_at",TS,nullable=False), _created(), sa.ForeignKeyConstraint(["tenant_id","adoption_id"],["tenant_baseline_adoptions.tenant_id","tenant_baseline_adoptions.id"]), sa.UniqueConstraint("tenant_id","id",name="uq_baseline_adoption_decision_tenant_id"))

    op.create_table("tenant_health_runs", _id(), _tenant(), sa.Column("status",sa.String(30),nullable=False), sa.Column("started_at",TS,nullable=False), sa.Column("completed_at",TS), sa.Column("summary",JSONB,nullable=False,server_default="{}"), _created(), sa.UniqueConstraint("tenant_id","id",name="uq_tenant_health_run_tenant_id"))
    op.create_table("tenant_service_health_checks", _id(), _tenant(), sa.Column("health_run_id",UUID,nullable=False), sa.Column("service",sa.String(60),nullable=False), sa.Column("status",sa.String(30),nullable=False), sa.Column("evidence",JSONB,nullable=False,server_default="{}"), sa.Column("checked_at",TS,nullable=False), _created(), sa.ForeignKeyConstraint(["tenant_id","health_run_id"],["tenant_health_runs.tenant_id","tenant_health_runs.id"]), sa.UniqueConstraint("tenant_id","health_run_id","service",name="uq_tenant_service_health_check"), sa.UniqueConstraint("tenant_id","id",name="uq_tenant_service_health_check_tenant_id"))
    op.create_table("tenant_isolation_evidence", _id(), _tenant(), sa.Column("health_run_id",UUID,nullable=False), sa.Column("boundary",sa.String(60),nullable=False), sa.Column("status",sa.String(30),nullable=False), sa.Column("evidence_reference",sa.String(500)), sa.Column("details",JSONB,nullable=False,server_default="{}"), sa.Column("checked_at",TS,nullable=False), _created(), sa.ForeignKeyConstraint(["tenant_id","health_run_id"],["tenant_health_runs.tenant_id","tenant_health_runs.id"]), sa.UniqueConstraint("tenant_id","health_run_id","boundary",name="uq_tenant_isolation_evidence"), sa.UniqueConstraint("tenant_id","id",name="uq_tenant_isolation_evidence_tenant_id"))
    op.create_table("platform_incidents", _id(), _tenant(True), sa.Column("incident_identifier",sa.String(60),nullable=False,unique=True), sa.Column("severity",sa.String(20),nullable=False), sa.Column("status",sa.String(30),nullable=False), sa.Column("title",sa.String(255),nullable=False), sa.Column("details",JSONB,nullable=False,server_default="{}"), sa.Column("opened_at",TS,nullable=False), sa.Column("resolved_at",TS), _created(), _updated())
    op.create_table("tenant_access_transitions", _id(), _tenant(), sa.Column("transition_type",sa.String(30),nullable=False), sa.Column("suspension_type",sa.String(30)), sa.Column("from_status",sa.String(30),nullable=False), sa.Column("to_status",sa.String(30),nullable=False), sa.Column("reason",sa.Text(),nullable=False), sa.Column("remarks",sa.Text(),nullable=False), sa.Column("effective_at",TS,nullable=False), sa.Column("notify_customer_admin",sa.Boolean(),nullable=False,server_default=sa.true()), sa.Column("performed_by",UUID,nullable=False), _created(), sa.UniqueConstraint("tenant_id","id",name="uq_tenant_access_transition_tenant_id"))
    op.create_index("ix_tenant_health_runs_status", "tenant_health_runs", ["tenant_id","status","started_at"]); op.create_index("ix_platform_incidents_status", "platform_incidents", ["status","severity","opened_at"])

    op.execute("""CREATE OR REPLACE FUNCTION mdarix_reject_immutable_identifier() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'IMMUTABLE_IDENTIFIER'; END $$;
      CREATE TRIGGER customers_identifier_immutable BEFORE UPDATE OF customer_identifier ON customers FOR EACH ROW WHEN (OLD.customer_identifier IS DISTINCT FROM NEW.customer_identifier) EXECUTE FUNCTION mdarix_reject_immutable_identifier();
      CREATE TRIGGER tenants_identifier_immutable BEFORE UPDATE OF tenant_identifier ON tenants FOR EACH ROW WHEN (OLD.tenant_identifier IS DISTINCT FROM NEW.tenant_identifier) EXECUTE FUNCTION mdarix_reject_immutable_identifier();
      CREATE TRIGGER environments_identifier_immutable BEFORE UPDATE OF environment_identifier ON tenant_environments FOR EACH ROW WHEN (OLD.environment_identifier IS DISTINCT FROM NEW.environment_identifier) EXECUTE FUNCTION mdarix_reject_immutable_identifier();""")
    op.execute("""DO $$ DECLARE r record; BEGIN FOR r IN SELECT table_name FROM information_schema.columns WHERE table_schema='public' AND column_name='tenant_id' AND table_name IN ('tenant_environments','identity_provider_configurations','support_access_grants','subscription_versions','license_transitions','grace_period_exceptions','plan_version_assignments','entitlement_snapshots','usage_quota_snapshots','renewal_requests','reminder_policy_recipients','tenant_baseline_adoptions','baseline_adoption_decisions','tenant_health_runs','tenant_service_health_checks','tenant_isolation_evidence','tenant_access_transitions') LOOP EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY',r.table_name); EXECUTE format('ALTER TABLE public.%I FORCE ROW LEVEL SECURITY',r.table_name); EXECUTE format('CREATE POLICY mdarix_tenant_isolation ON public.%I USING (tenant_id = NULLIF(current_setting(''app.tenant_id'',true),'''')::uuid) WITH CHECK (tenant_id = NULLIF(current_setting(''app.tenant_id'',true),'''')::uuid)',r.table_name); END LOOP; END $$;""")
    op.execute("""DO $$ BEGIN IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname='mdarix_runtime') THEN GRANT SELECT,INSERT,UPDATE,DELETE ON ALL TABLES IN SCHEMA public TO mdarix_runtime; GRANT USAGE,SELECT,UPDATE ON ALL SEQUENCES IN SCHEMA public TO mdarix_runtime; END IF; END $$;""")


def downgrade():
    op.execute("DROP TRIGGER IF EXISTS environments_identifier_immutable ON tenant_environments; DROP TRIGGER IF EXISTS tenants_identifier_immutable ON tenants; DROP TRIGGER IF EXISTS customers_identifier_immutable ON customers")
    for table in ("tenant_access_transitions","platform_incidents","tenant_isolation_evidence","tenant_service_health_checks","tenant_health_runs","baseline_adoption_decisions","baseline_differences","tenant_baseline_adoptions","configuration_baseline_versions","configuration_baselines","provisioning_job_steps","provisioning_jobs","customer_onboarding_drafts","reminder_policy_recipients","renewal_requests","usage_quota_snapshots","entitlement_snapshots","plan_version_assignments","grace_period_exceptions","license_transitions","subscription_versions","support_access_grants","identity_provider_configurations","domain_verifications","customer_domains","customer_contacts","tenant_environments"):
        op.drop_table(table)
    op.drop_index("ix_subscription_lifecycles_expiry", table_name="subscription_lifecycles")
    op.drop_constraint("uq_subscription_reminder_policy_tenant_id", "subscription_reminder_policies", type_="unique")
    op.drop_index("ix_tenants_customer_status_region", table_name="tenants")
    for kind, name in (("check","tenant_type_allowed"),("check","tenant_provisioning_status_allowed"),("check","tenant_lifecycle_status_allowed"),("unique","uq_tenants_customer_id_id"),("unique","uq_tenants_tenant_slug"),("unique","uq_tenants_tenant_identifier"),("foreignkey","fk_tenants_customer_id_customers")):
        op.drop_constraint(name, "tenants", type_=kind)
    for name in ("lock_version","terminated_at","suspended_at","activated_at","provisioning_status","configuration_version","schema_version","application_version","cross_border_processing_allowed","disaster_recovery_region","ai_processing_region","storage_region","backup_region","database_region","residency_region","primary_region","deployment_model","tenant_type","tenant_slug","display_name","tenant_identifier","customer_id"):
        op.drop_column("tenants", name)
    op.drop_index("ix_customers_directory", table_name="customers"); op.drop_table("customers")
    op.execute("DROP FUNCTION IF EXISTS mdarix_reject_immutable_identifier()")
