"""add deterministic AI trust assurance"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
revision="e18a2b3c4d01"; down_revision="d17b1e4c8a01"; branch_labels=None; depends_on=None
def upgrade():
    uuid=postgresql.UUID(as_uuid=True)
    op.create_table("assurance_results", sa.Column("id",uuid,server_default=sa.text("gen_random_uuid()"),nullable=False),sa.Column("tenant_id",uuid,nullable=False),sa.Column("investigation_id",uuid),sa.Column("ai_execution_id",uuid,nullable=False),sa.Column("output_type",sa.String(80),nullable=False),sa.Column("output_id",sa.String(255)),sa.Column("assurance_version",sa.Integer(),server_default="1",nullable=False),sa.Column("status",sa.String(40),nullable=False),sa.Column("generated_at",sa.DateTime(timezone=True)),sa.Column("trust_policy_version",sa.String(120),nullable=False),sa.Column("product_id",uuid),sa.Column("product_version_id",uuid),sa.Column("temporal_mode",sa.String(20)),sa.Column("temporal_cutoff",sa.DateTime(timezone=True)),sa.Column("human_review_required",sa.Boolean(),server_default="true",nullable=False),sa.Column("revalidation_required",sa.Boolean(),server_default="false",nullable=False),sa.Column("limitations",postgresql.JSONB()),sa.Column("configuration_hash",sa.String(64)),sa.Column("created_at",sa.DateTime(timezone=True)),sa.ForeignKeyConstraint(["tenant_id","ai_execution_id"],["ai_executions.tenant_id","ai_executions.id"]),sa.PrimaryKeyConstraint("id"),sa.UniqueConstraint("tenant_id","id",name="uq_assurance_results_tenant_id_id"))
    op.create_table("assurance_checks",sa.Column("id",uuid,server_default=sa.text("gen_random_uuid()"),nullable=False),sa.Column("tenant_id",uuid,nullable=False),sa.Column("assurance_result_id",uuid,nullable=False),sa.Column("check_type",sa.String(80),nullable=False),sa.Column("status",sa.String(40),nullable=False),sa.Column("severity",sa.String(20),nullable=False),sa.Column("message",sa.Text(),nullable=False),sa.Column("evidence_reference",postgresql.JSONB()),sa.Column("details",postgresql.JSONB()),sa.Column("created_at",sa.DateTime(timezone=True)),sa.ForeignKeyConstraint(["tenant_id","assurance_result_id"],["assurance_results.tenant_id","assurance_results.id"]),sa.PrimaryKeyConstraint("id"),sa.UniqueConstraint("tenant_id","id",name="uq_assurance_checks_tenant_id_id"))
def downgrade(): op.drop_table("assurance_checks"); op.drop_table("assurance_results")
