"""add Day 23 governance and electronic signature foundation"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
revision="h23d4e5f6a01"; down_revision="g22c3d4e5f01"; branch_labels=None; depends_on=None
def uid(): return sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True, server_default=sa.text("gen_random_uuid()"))
def times(): return [sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False)]
def upgrade():
 op.create_table("plan_definitions",uid(),sa.Column("code",sa.String(80),nullable=False,unique=True),sa.Column("name",sa.String(120),nullable=False),sa.Column("description",sa.Text()),sa.Column("version",sa.String(40),nullable=False),sa.Column("status",sa.String(30),nullable=False),sa.Column("effective_from",sa.DateTime(timezone=True),nullable=False),sa.Column("effective_to",sa.DateTime(timezone=True)),*times())
 op.create_table("feature_entitlements",uid(),sa.Column("plan_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("plan_definitions.id"),nullable=False),sa.Column("feature_code",sa.String(120),nullable=False),sa.Column("enabled",sa.Boolean(),nullable=False),sa.Column("limits",postgresql.JSONB()),sa.Column("status",sa.String(30),nullable=False),*times(),sa.UniqueConstraint("plan_id","feature_code",name="uq_plan_feature_entitlement"))
 for table, cols in [("tenant_plan_assignments",[sa.Column("tenant_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("tenants.id"),nullable=False),sa.Column("plan_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("plan_definitions.id"),nullable=False),sa.Column("status",sa.String(30),nullable=False),sa.Column("effective_from",sa.DateTime(timezone=True),nullable=False),sa.Column("effective_to",sa.DateTime(timezone=True)),sa.Column("reason",sa.Text())]),("approval_authorities",[sa.Column("tenant_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("tenants.id"),nullable=False),sa.Column("role_name",sa.String(120),nullable=False),sa.Column("object_type",sa.String(120),nullable=False),sa.Column("decision_type",sa.String(120),nullable=False),sa.Column("scope",postgresql.JSONB()),sa.Column("authority",sa.String(30),nullable=False),sa.Column("version",sa.String(40),nullable=False),sa.Column("status",sa.String(30),nullable=False),sa.Column("effective_from",sa.DateTime(timezone=True),nullable=False),sa.Column("effective_to",sa.DateTime(timezone=True))]),("segregation_of_duties_policies",[sa.Column("tenant_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("tenants.id"),nullable=False),sa.Column("name",sa.String(160),nullable=False),sa.Column("object_type",sa.String(120),nullable=False),sa.Column("decision_type",sa.String(120),nullable=False),sa.Column("creator_cannot_approve",sa.Boolean(),nullable=False),sa.Column("last_material_editor_cannot_approve",sa.Boolean(),nullable=False),sa.Column("version",sa.String(40),nullable=False),sa.Column("status",sa.String(30),nullable=False),sa.Column("effective_from",sa.DateTime(timezone=True),nullable=False),sa.Column("effective_to",sa.DateTime(timezone=True))])]: op.create_table(table,uid(),*cols,*times())
 op.create_table("signed_approval_records",uid(),sa.Column("tenant_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("tenants.id"),nullable=False),sa.Column("object_type",sa.String(120),nullable=False),sa.Column("object_id",postgresql.UUID(as_uuid=True),nullable=False),sa.Column("object_version",sa.String(80),nullable=False),sa.Column("decision_type",sa.String(120),nullable=False),sa.Column("decision",sa.String(12),nullable=False),sa.Column("remarks",sa.Text(),nullable=False),sa.Column("signer_user_id",sa.String(254),nullable=False),sa.Column("signer_role",sa.String(120),nullable=False),sa.Column("signature_meaning",sa.Text(),nullable=False),sa.Column("content_fingerprint",sa.String(64),nullable=False),sa.Column("signature_hash",sa.String(64),nullable=False),sa.Column("status",sa.String(30),nullable=False),sa.Column("signed_at",sa.DateTime(timezone=True),nullable=False),sa.Column("invalidated_at",sa.DateTime(timezone=True)),sa.Column("invalidation_reason",sa.Text()),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("tenant_id","object_type","object_id","object_version","decision_type",name="uq_signed_approval_version"))
def downgrade():
 for n in ["signed_approval_records","segregation_of_duties_policies","approval_authorities","tenant_plan_assignments","feature_entitlements","plan_definitions"]: op.drop_table(n)
