"""add Day 25 persistent connector run and reconciliation records"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
revision="i25enterprise"; down_revision="h23d4e5f6a01"; branch_labels=None; depends_on=None
def uid(): return sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True, server_default=sa.text("gen_random_uuid()"))
def tenant(): return sa.Column("tenant_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("tenants.id"),nullable=False)
def ts(name, nullable=True): return sa.Column(name,sa.DateTime(timezone=True),nullable=nullable)
def upgrade():
    op.create_table("connector_runs",uid(),tenant(),sa.Column("connection_id",sa.String(160),nullable=False),sa.Column("source_system",sa.String(120),nullable=False),sa.Column("run_type",sa.String(40),nullable=False,server_default="INCREMENTAL"),sa.Column("status",sa.String(30),nullable=False,server_default="PENDING"),sa.Column("records_received",sa.Integer(),nullable=False,server_default="0"),sa.Column("records_accepted",sa.Integer(),nullable=False,server_default="0"),sa.Column("records_rejected",sa.Integer(),nullable=False,server_default="0"),sa.Column("records_quarantined",sa.Integer(),nullable=False,server_default="0"),sa.Column("records_duplicate",sa.Integer(),nullable=False,server_default="0"),sa.Column("retry_attempt",sa.Integer(),nullable=False,server_default="0"),sa.Column("reconciliation_status",sa.String(40)),sa.Column("schema_drift_status",sa.String(40)),sa.Column("failure_category",sa.String(60)),sa.Column("correlation_id",sa.String(120)),ts("started_at",False),ts("completed_at"),ts("created_at",False))
    op.create_table("connector_source_records",uid(),tenant(),sa.Column("connector_run_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("connector_runs.id"),nullable=False),sa.Column("source_system",sa.String(120),nullable=False),sa.Column("source_record_id",sa.String(255),nullable=False),sa.Column("source_record_version",sa.String(120)),sa.Column("fingerprint",sa.String(64),nullable=False),sa.Column("processing_status",sa.String(40),nullable=False),sa.Column("quarantine_reason",sa.Text()),ts("effective_at"),ts("ingested_at",False),ts("created_at",False),sa.UniqueConstraint("tenant_id","source_system","source_record_id","source_record_version",name="uq_connector_source_record_identity"))
    op.create_table("connector_reconciliations",uid(),tenant(),sa.Column("connector_run_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("connector_runs.id"),nullable=False),sa.Column("expected_count",sa.Integer(),nullable=False),sa.Column("received_count",sa.Integer(),nullable=False),sa.Column("accepted_count",sa.Integer(),nullable=False),sa.Column("rejected_count",sa.Integer(),nullable=False),sa.Column("quarantined_count",sa.Integer(),nullable=False),sa.Column("duplicate_count",sa.Integer(),nullable=False),sa.Column("unresolved_count",sa.Integer(),nullable=False,server_default="0"),sa.Column("status",sa.String(40),nullable=False),sa.Column("details",postgresql.JSONB()),ts("reconciled_at",False),ts("created_at",False))
def downgrade():
    op.drop_table("connector_reconciliations"); op.drop_table("connector_source_records"); op.drop_table("connector_runs")
