import { useEffect, useMemo, useState } from "react";

type Item = Record<string, any>;
const request = async <T,>(url: string, init?: RequestInit): Promise<T> => {
  const response = await fetch(url, init);
  const body = await response.json().catch(() => ({}));
  if (!response.ok) throw new Error(body.detail?.message ?? "Mapping Studio request failed");
  return body;
};

export function MappingStudio() {
  const [apps, setApps] = useState<Item[]>([]), [objects, setObjects] = useState<Item[]>([]), [fields, setFields] = useState<Item[]>([]);
  const [entities, setEntities] = useState<Item[]>([]), [masters, setMasters] = useState<Item[]>([]), [versions, setVersions] = useState<Item[]>([]), [connectorVersions, setConnectorVersions] = useState<Item[]>([]);
  const [app, setApp] = useState("TRACKWISE"), [object, setObject] = useState("TRACKWISE:COMPLAINT"), [entity, setEntity] = useState("Complaint");
  const [masterId, setMasterId] = useState(""), [versionId, setVersionId] = useState(""), [version, setVersion] = useState("M1");
  const [status, setStatus] = useState("DRAFT"), [rows, setRows] = useState<Item[]>([]), [sample, setSample] = useState('{"complaint_number":"CMP-001","product_code":"P-100"}');
  const [message, setMessage] = useState(""), [error, setError] = useState(""), [validation, setValidation] = useState<Item | null>(null), [dryRunResult, setDryRunResult] = useState<Item | null>(null), [discovery, setDiscovery] = useState<Item | null>(null);
  const [sourceSearch, setSourceSearch] = useState(""), [selectedRow, setSelectedRow] = useState<number | null>(null), [previewTab, setPreviewTab] = useState("source");

  const load = async () => {
    try {
      const [a, e, master, persisted] = await Promise.all([
        request<Item[]>("/api/v1/admin/mapping/applications"), request<Item[]>("/api/v1/admin/mapping/canonical/entities"),
        request<Item[]>("/api/v1/admin/catalog/master-mappings"), request<Item[]>("/api/v1/admin/catalog/mapping-versions"),
      ]);
      setApps(a); setEntities(e); setMasters(master); setVersions(persisted);
      if (!masterId && master[0]) setMasterId(master[0].id);
    } catch (e) { setError((e as Error).message); }
  };
  useEffect(() => { void load(); }, []);
  useEffect(() => {
    void request<Item[]>(`/api/v1/admin/mapping/applications/${app}/objects`).then(setObjects).catch(e => setError(e.message));
  }, [app]);
  useEffect(() => { void request<Item[]>(`/api/v1/admin/mapping/connector-versions?application_id=${encodeURIComponent(app)}`).then(setConnectorVersions).catch(e => setError(e.message)); }, [app]);
  useEffect(() => { if (object) void request<Item[]>(`/api/v1/admin/mapping/objects/${object}/fields`).then(setFields).catch(e => setError(e.message)); }, [object]);
  useEffect(() => { if (entity) void request<Item[]>(`/api/v1/admin/mapping/canonical/entities/${entity}/fields`).then(setFieldsForEntity).catch(e => setError(e.message)); }, [entity]);
  const [canonical, setCanonical] = useState<Item[]>([]);
  const setFieldsForEntity = (items: Item[]) => setCanonical(items);
  useEffect(() => { const selected = versions.find(v => v.id === versionId); if (selected) { setRows(selected.rules ?? []); setVersion(selected.version); setStatus(selected.status); } }, [versionId, versions]);

  useEffect(() => { const candidates = versions.filter(v => v.master_mapping_id === masterId); if (!versionId && candidates[0]) setVersionId(candidates[0].id); }, [masterId, versions, versionId]);
  const health = useMemo(() => {
    const targets = rows.map(r => r.target);
    const required = canonical.filter(f => f.required && f.mapping_allowed !== false).map(f => f.field_name);
    return { missing: required.filter(f => !targets.includes(f)), protected: rows.filter(r => canonical.some(f => f.field_name === r.target && f.mapping_allowed === false)).length, mapped: new Set(targets).size, warnings: rows.filter(r => r.transform === "REFERENCE_LOOKUP" || r.null_rule === "PRESERVE_UNKNOWN").length };
  }, [rows, canonical]);
  const visibleFields = useMemo(() => fields.filter(field => `${field.field_name} ${field.field_group} ${field.data_type}`.toLowerCase().includes(sourceSearch.toLowerCase())), [fields, sourceSearch]);
  const clearNotice = () => { setError(""); setMessage(""); };
  const addRow = () => { clearNotice(); setRows(old => [...old, { source: fields[0]?.field_name ?? "", target: canonical.find(f => f.mapping_allowed !== false)?.field_name ?? "", transform: "DIRECT_COPY", required: false, null_rule: "PRESERVE_UNKNOWN", source_priority: "AUTHORITATIVE", override_policy: "TENANT_ALLOWED" }]); };
  const updateRow = (index: number, key: string, value: string) => setRows(old => old.map((row, i) => i === index ? { ...row, [key]: value } : row));
  const saveVersion = async () => { try { clearNotice(); const result = await request<Item>("/api/v1/admin/catalog/mapping-versions", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ master_mapping_id: masterId, version, rules: rows }) }); setVersionId(result.id); setMessage(`Draft ${version} saved with authenticated audit evidence.`); await load(); } catch (e) { setError((e as Error).message); } };
  const validate = async () => { try { clearNotice(); const result = await request<Item>("/api/v1/admin/mapping/validate", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ entity_id: entity, rules: rows }) }); setValidation(result); setMessage(`Server validation completed: ${result.status}.`); } catch (e) { setError((e as Error).message); } };
  const dryRun = async () => { try { clearNotice(); const parsed = JSON.parse(sample); const result = await request<Item>("/api/v1/admin/mapping/dry-run", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ source_object_id: object, rules: rows, records: Array.isArray(parsed) ? parsed : [parsed] }) }); setDryRunResult(result); setMessage(`Dry-run completed: ${result.outcome}. No database write occurred.`); } catch (e) { setError((e as Error).message); } };
  const refreshSchema = async () => { try { clearNotice(); const result = await request<Item>("/api/v1/admin/mapping/schema-discovery", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ source_object_id: object, baseline_fields: fields, fields }) }); setDiscovery(result); setMessage(`Schema review completed: ${result.schema_status}. No fields were auto-applied.`); } catch (e) { setError((e as Error).message); } };
  const compare = async () => { const selected = versions.filter(v => v.master_mapping_id === masterId); if (selected.length < 2) { setMessage("Create at least two persisted versions before comparing."); return; } try { const result = await request<Item>("/api/v1/admin/mapping/compare", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ master_mapping_id: masterId, from_version: selected[1].version, to_version: selected[0].version, from_rules: selected[1].rules ?? [], to_rules: selected[0].rules ?? [] }) }); setMessage(`Comparison persisted: ${result.impact.affected_rules} affected rule(s).`); } catch (e) { setError((e as Error).message); } };
  const approve = async () => { try { clearNotice(); const result = await request<Item>(`/api/v1/admin/catalog/mapping-versions/${versionId}/status`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ status: "APPROVED" }) }); setStatus(result.status); setMessage("Approval recorded with authenticated audit evidence."); } catch (e) { setError((e as Error).message); } };
  const release = async () => { if (!validation || validation.status !== "PASS" || health.missing.length || health.protected) { setError("Run a passing server validation before release."); return; } try { clearNotice(); const result = await request<Item>(`/api/v1/admin/catalog/master-mappings/${masterId}/status`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ status: "RELEASED" }) }); setStatus(result.status); setMessage("Mapping released. The released version is immutable."); } catch (e) { setError((e as Error).message); } };

  return <div className="content mapping-studio-page">
    <section className="mapping-hero"><div><p className="eyebrow">ADMINISTRATOR CONTROL PLANE / MAPPING</p><h1>Master Mapping Studio</h1><p>Configure external application fields against the governed MDARIX canonical model. Every release is validated, approved, versioned, and audited.</p></div><div className="mapping-badge">{status} · {object}</div></section>
    {error && <div className="error" role="alert">{error}</div>}{message && <div className="success" role="status">{message}</div>}
    <section className="mapping-panel mapping-context-summary"><div><span className="eyebrow">CONFIGURATION CONTEXT</span><strong>{apps.find(a => a.application_id === app)?.display_name ?? app}</strong><span>{objects.find(o => o.source_object_id === object)?.object_name ?? object}</span></div><div><span className="eyebrow">CONNECTOR VERSION</span><strong>{connectorVersions[0]?.version ?? "Not configured"}</strong><span>{connectorVersions[0]?.supports_schema_discovery ? "Schema discovery available" : "Schema discovery unavailable"}</span></div><div><span className="eyebrow">MASTER MAPPING</span><strong>{masters.find(m => m.id === masterId)?.code ?? "Not selected"}</strong><span>{version} Â· {status}</span></div><div><span className="eyebrow">TARGET</span><strong>{entity}</strong><span>Tenant-scoped canonical model</span></div></section>
    <section className="mapping-panel mapping-selector-grid"><label>External application<select value={app} onChange={e => setApp(e.target.value)}>{apps.map(a => <option key={a.application_id} value={a.application_id}>{a.display_name}</option>)}</select></label><label>Source object<select value={object} onChange={e => setObject(e.target.value)}>{objects.map(o => <option key={o.source_object_id} value={o.source_object_id}>{o.object_name}</option>)}</select></label><label>Master mapping<select value={masterId} onChange={e => setMasterId(e.target.value)}>{masters.map(m => <option key={m.id} value={m.id}>{m.code} · {m.status}</option>)}</select></label><label>Mapping version<input value={version} onChange={e => setVersion(e.target.value)} disabled={Boolean(versionId)} /></label><label>Canonical entity<select value={entity} onChange={e => setEntity(e.target.value)}>{entities.map(e => <option key={e.entity_id} value={e.entity_id}>{e.entity_name}</option>)}</select></label></section>
    <section className="mapping-panel"><h2>Mapping lifecycle</h2><div className="mapping-actions"><button className="secondary" onClick={addRow}>Add mapping row</button><button className="secondary" onClick={validate}>Validate</button><button className="secondary" onClick={dryRun}>Run dry test</button><button className="secondary" onClick={refreshSchema}>Refresh source schema</button><button className="secondary" onClick={compare}>Compare versions</button><button onClick={saveVersion} disabled={!masterId || status === "RELEASED"}>Save draft</button><button onClick={approve} disabled={!versionId || status === "RELEASED"}>Approve</button><button onClick={release} disabled={!masterId || status === "RELEASED"}>Release</button></div></section>
    <section className="mapping-panel mapping-health"><article><span>Source fields</span><strong>{fields.length}</strong></article><article><span>Mapped fields</span><strong>{rows.length}</strong></article><article><span>Required missing</span><strong>{health.missing.length}</strong></article><article><span>Protected violations</span><strong>{health.protected}</strong></article></section>
    <section className="mapping-columns"><div className="mapping-panel"><h2>Source schema</h2><input value={sourceSearch} onChange={e => setSourceSearch(e.target.value)} placeholder="Search source fields..." aria-label="Search source fields"/><div className="mapping-list">{visibleFields.map(f => <article key={f.source_field_id}><strong>{f.field_name}</strong><span>{f.field_group} · {f.data_type}{f.required ? " · Required" : ""}</span></article>)}</div></div><div className="mapping-panel"><h2>Mapping sheet</h2><div className="mapping-table-head">Source field → target field · transformation · controls</div>{rows.length === 0 && <p className="muted">No draft rows yet. Add a mapping row to begin.</p>}{rows.map((row, i) => <button className={`mapping-row mapping-row-button ${selectedRow === i ? "selected" : ""}`} key={i} onClick={() => setSelectedRow(i)}><select aria-label={`Source field ${i + 1}`} value={row.source} onClick={e => e.stopPropagation()} onChange={e => updateRow(i, "source", e.target.value)}>{fields.map(f => <option key={f.field_name}>{f.field_name}</option>)}</select><span>→</span><select aria-label={`Target field ${i + 1}`} value={row.target} onClick={e => e.stopPropagation()} onChange={e => updateRow(i, "target", e.target.value)}>{canonical.filter(f => f.mapping_allowed !== false).map(f => <option key={f.field_name}>{f.field_name}</option>)}</select><select aria-label={`Transformation ${i + 1}`} value={row.transform} onClick={e => e.stopPropagation()} onChange={e => updateRow(i, "transform", e.target.value)}><option>DIRECT</option><option>TRIM</option><option>UPPER</option><option>LOWER</option><option>DATE_ISO8601</option><option>REFERENCE_LOOKUP</option><option>ENUM_MAP</option></select></button>)}</div><div className="mapping-panel"><h2>Canonical model</h2><div className="mapping-list">{canonical.map(f => <article key={f.canonical_field_id}><strong>{f.field_name}</strong><span>{f.mapping_allowed === false ? "PLATFORM ONLY" : f.required ? "Required" : "Optional"}</span></article>)}</div></div></section>
    {selectedRow !== null && <aside className="mapping-drawer" aria-label="Mapping detail"><button className="drawer-close" onClick={() => setSelectedRow(null)}>Close</button><h2>Mapping detail</h2><p className="eyebrow">ROW {selectedRow + 1} · HUMAN CONFIGURATION REQUIRED</p><dl><dt>Source field</dt><dd>{rows[selectedRow]?.source}</dd><dt>Source type</dt><dd>{fields.find(f => f.field_name === rows[selectedRow]?.source)?.data_type ?? "-"}</dd><dt>Canonical entity</dt><dd>{entity}</dd><dt>Target field</dt><dd>{rows[selectedRow]?.target}</dd><dt>Transformation</dt><dd>{rows[selectedRow]?.transform}</dd><dt>Override policy</dt><dd>{rows[selectedRow]?.override_policy ?? "CUSTOMER_OVERRIDE_ALLOWED"}</dd></dl><p className="muted">Protected fields are excluded from the target catalog and are blocked server-side.</p></aside>}
    <section className="mapping-panel"><h2>Preview and evidence</h2><div className="mapping-tabs"><button className={previewTab === "source" ? "active" : "secondary"} onClick={() => setPreviewTab("source")}>Source payload</button><button className={previewTab === "transformed" ? "active" : "secondary"} onClick={() => setPreviewTab("transformed")}>Transformed preview</button><button className={previewTab === "validation" ? "active" : "secondary"} onClick={() => setPreviewTab("validation")}>Validation / provenance</button></div>{previewTab === "source" && <textarea value={sample} onChange={e => setSample(e.target.value)} aria-label="Sample source payload"/>}{previewTab === "transformed" && <pre className="mapping-json">{JSON.stringify(dryRunResult?.records ?? [], null, 2)}</pre>}{previewTab === "validation" && <pre className="mapping-json">{JSON.stringify({ validation, discovery, persisted_write: false }, null, 2)}</pre>}<p className="muted">Dry-run is a no-write operation. Schema refresh is review-only. Released mappings cannot be edited.</p>{validation && <div className="mapping-result"><strong>Validation: {validation.status}</strong><div>Errors: {validation.errors?.length ?? 0} · Missing required: {validation.missing_required?.length ?? 0} · Rules checked: {validation.checked_rules}</div></div>}{dryRunResult && <div className="mapping-result"><strong>Dry-run: {dryRunResult.outcome}</strong><div>Records: {dryRunResult.record_count} · Passed: {dryRunResult.passed} · Warnings: {dryRunResult.warnings} · Blocked: {dryRunResult.blocked} · Persisted: {String(dryRunResult.persisted)}</div></div>}{discovery && <div className="mapping-result"><strong>Schema: {discovery.schema_status}</strong><div>Changes detected: {discovery.changes?.length ?? 0} · Automatically applied: {String(discovery.auto_applied)}</div></div>}</section>
  </div>;
}
