import { useEffect, useState } from "react";
type Configuration = { tenant: any; products: any[]; versions: any[]; connectors: any[]; mapping_versions: any[] };
export function PlatformProductConfiguration() {
  const [customers, setCustomers] = useState<any[]>([]); const [tenantId, setTenantId] = useState(""); const [data, setData] = useState<Configuration | null>(null); const [error, setError] = useState("");
  const loadCustomers = async () => { const r = await fetch("/api/v1/platform-admin/customers"); if (!r.ok) throw new Error("Customer directory unavailable"); const rows = await r.json(); setCustomers(rows); if (!tenantId && rows[0]) setTenantId(rows[0].id); };
  const load = async (id: string) => { if (!id) return; const r = await fetch(`/api/v1/platform/product-configuration/${encodeURIComponent(id)}`); const b = await r.json(); if (!r.ok) throw new Error(b.detail?.message ?? "Product configuration unavailable"); setData(b); };
  useEffect(() => { void loadCustomers().catch(e => setError(e.message)); }, []); useEffect(() => { void load(tenantId).catch(e => setError(e.message)); }, [tenantId]);
  return <div className="content governance-view admin-page"><section className="product-header"><div><p className="eyebrow">PLATFORM ADMINISTRATION</p><h2>Product Configuration</h2><p>Control each customer’s product and version baseline, connector binding, and mapping release without exposing secrets or crossing tenant boundaries.</p></div><div className="version-pill">Platform-scoped · audited</div></section>{error && <div className="error" role="alert">{error}</div>}<section className="panel"><label htmlFor="configuration-tenant"><strong>Customer tenant</strong></label><select id="configuration-tenant" value={tenantId} onChange={e => setTenantId(e.target.value)}><option value="">Select a customer</option>{customers.map(c => <option key={c.id} value={c.id}>{c.name} · {c.tenant_key}</option>)}</select>{data && <span className="version-pill">{data.tenant.status} · {data.tenant.tenant_key}</span>}</section>{data && <><section className="home-insight-grid">{[["Products", data.products.length], ["Product versions", data.versions.length], ["Connectors", data.connectors.length], ["Mapping versions", data.mapping_versions.length]].map(([label, count]) => <article key={String(label)}><span className="eyebrow">{label}</span><strong>{count}</strong><p>Server-derived tenant configuration</p></article>)}</section><section className="panel"><div className="section-title">Products and versions</div><div className="evidence-list">{data.products.map(p => <article key={p.id}><strong>{p.name}</strong><span>{p.identifier} · {p.status}</span><small>{data.versions.filter(v => v.product_id === p.id).map(v => `${v.identifier} (${v.status})`).join(" · ") || "No versions registered"}</small></article>)}</div></section><section className="panel"><div className="section-title">External API connectors</div><p>Endpoint metadata is visible for operations; credential values are never returned.</p><div className="evidence-list">{data.connectors.map(c => <article key={c.id}><strong>{c.code} · {c.status}</strong><span>{c.connector_type} · {c.version}</span><small>{c.endpoint || "Endpoint not configured"} · credential {c.credential_configured ? "configured" : "not configured"}</small></article>)}</div></section><section className="panel"><div className="section-title">Mapping release baseline</div><div className="evidence-list">{data.mapping_versions.map(m => <article key={m.id}><strong>{m.version} · {m.status}</strong><span>Master mapping {m.master_mapping_id}</span><small>{Object.keys(m.rules || {}).length} governed field rule(s)</small></article>)}</div></section></>}</div>;
}
