import { useEffect, useState } from "react";
type Customer = { id: string; name: string; tenant_key: string };
export function SubscriptionAdministration() {
  const [customers, setCustomers] = useState<Customer[]>([]); const [tenantId, setTenantId] = useState(""); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  const [policy, setPolicy] = useState({ name: "Standard renewal reminders", thresholds: "60,30,7", timezone: "UTC" });
  const [template, setTemplate] = useState({ stage: "30_DAY", subject: "MDARIX subscription renewal reminder", body: "Hello {{customer_name}}, your subscription expires on {{expiry_date}}.", version: "v1" });
  useEffect(() => { fetch("/api/v1/platform/customers", { credentials: "include" }).then((r) => r.ok ? r.json() : Promise.reject(new Error("Customer directory unavailable"))).then(setCustomers).catch((e) => setError(e.message)); }, []);
  const post = async (url: string, body: unknown) => { const r = await fetch(url, { method: "POST", credentials: "include", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const data = await r.json(); if (!r.ok) throw new Error(data.detail?.message ?? "Request failed"); return data; };
  const savePolicy = async () => { if (!tenantId) return setError("Select a customer tenant first."); try { const r = await post(`/api/v1/platform/subscriptions/${tenantId}/reminder-policies`, { name: policy.name, thresholds: policy.thresholds.split(",").map(Number), timezone: policy.timezone, recipient_types: ["CUSTOMER_ADMIN"], version: "v1" }); setMessage(`Reminder policy ${r.version} saved.`); setError(""); } catch (e) { setError((e as Error).message); } };
  const saveTemplate = async () => { if (!tenantId) return setError("Select a customer tenant first."); try { const r = await post(`/api/v1/platform/subscriptions/${tenantId}/email-templates`, { ...template, allowed_variables: ["customer_name", "expiry_date", "days_remaining"] }); setMessage(`Email template ${r.stage} ${r.version} saved as ${r.status}.`); setError(""); } catch (e) { setError((e as Error).message); } };
  const runLifecycle = async () => { try { const r = await post("/api/v1/platform/subscriptions/lifecycle/run", {}); setMessage(`Lifecycle run complete: ${r.queued} reminder(s) queued, ${r.transitioned} transition(s).`); setError(""); } catch (e) { setError((e as Error).message); } };
  return <div className="content governance-view subscription-admin-page"><section className="governance-hero"><div><span className="eyebrow">Platform administration</span><h2>Subscriptions &amp; notifications</h2><p>Manage plan lifecycle, renewal reminders, and approved communication templates without exposing customer business data.</p></div><div className="governance-status"><strong>Commercial controls</strong><span>Platform Administrator only · audited</span></div></section><section className="panel subscription-toolbar"><label>Customer tenant<select value={tenantId} onChange={(e) => setTenantId(e.target.value)}><option value="">Select customer</option>{customers.map((c) => <option key={c.id} value={c.id}>{c.name} ({c.tenant_key})</option>)}</select></label><button className="primary-action" onClick={runLifecycle}>Run lifecycle check</button></section>{message && <p className="review-success" role="status">{message}</p>}{error && <p className="field-error" role="alert">{error}</p>}<section className="subscription-admin-grid"><article className="panel"><div className="section-title">Reminder policies</div><p>Define ordered expiry thresholds and recipient classes. Thresholds are validated and versioned by the server.</p><label>Policy name<input value={policy.name} onChange={(e) => setPolicy({ ...policy, name: e.target.value })} /></label><label>Thresholds in days<input value={policy.thresholds} onChange={(e) => setPolicy({ ...policy, thresholds: e.target.value })} /><small>Example: 60,30,7</small></label><label>Timezone<input value={policy.timezone} onChange={(e) => setPolicy({ ...policy, timezone: e.target.value })} /></label><button className="primary-action" onClick={savePolicy}>Save reminder policy</button></article><article className="panel"><div className="section-title">Email templates</div><p>Draft versioned renewal messages using approved merge variables. Delivery is tracked by the provider.</p><label>Stage<select value={template.stage} onChange={(e) => setTemplate({ ...template, stage: e.target.value })}><option>60_DAY</option><option>30_DAY</option><option>7_DAY</option><option>GRACE</option><option>EXPIRED</option></select></label><label>Version<input value={template.version} onChange={(e) => setTemplate({ ...template, version: e.target.value })} /></label><label>Subject<input value={template.subject} onChange={(e) => setTemplate({ ...template, subject: e.target.value })} /></label><label>Body<textarea rows={5} value={template.body} onChange={(e) => setTemplate({ ...template, body: e.target.value })} /></label><small>Allowed variables: customer_name, expiry_date, days_remaining</small><button className="primary-action" onClick={saveTemplate}>Save email template</button></article></section></div>;
}
