import React, { useEffect, useState } from "react";
import { ChevronRight } from "lucide-react";

type MenuItem = { label: string; href: string; future?: boolean; description?: string };
type MenuGroup = { title: string; items: MenuItem[] };
const current = (label: string, href: string, description?: string): MenuItem => ({ label, href, description });
const future = (label: string, anchor: string): MenuItem => ({ label, href: `/platform/${anchor}` });

const menus: Record<string, MenuGroup[]> = {
  Platform: [
    { title: "Product Intelligence", items: [current("Product 360", "/platform/product-360", "See product, version, configuration, and lifecycle context."), current("Product Reality Graph", "/platform/reality-graph", "Connect product, supplier, lot, complaint, change, and evidence relationships."), current("ProductVersion Intelligence", "/platform/product-version", "Compare revisions, scope, and impact with traceable context."), current("Timeline Intelligence", "/platform/timeline", "Understand what changed, when it became effective, and when it became known.")] },
    { title: "Investigation Intelligence", items: [current("Ask MDARIX", "/platform/ask-mdarix", "Ask a controlled investigation question and preserve its scope."), current("Investigation Workspace", "/platform/investigation"), current("Evidence Intelligence", "/platform/evidence"), current("Hypothesis Intelligence", "/platform/hypotheses"), current("AI Challenger", "/platform/challenger"), current("Unknowns Radar", "/platform/unknowns")] },
    { title: "Decision Intelligence", items: [current("Failure Chain Intelligence", "/platform/failure-chain"), current("Counterfactual Analysis", "/platform/counterfactual"), current("Decision Center", "/platform/decision-center"), current("Investigation Brief", "/platform/investigation-brief")] },
    { title: "Trust & Governance", items: [current("AI Assurance", "/platform/ai-assurance"), current("AI Provenance", "/platform/ai-provenance"), current("Human Review & Approval", "/platform/human-review"), current("Audit Trail", "/platform/audit-trail"), current("Enterprise Administration", "/platform/enterprise-administration")] },
  ],
  Solutions: [
    { title: "By Challenge", items: [current("Investigate Complaint Increases", "/solutions#complaints"), current("Understand Product Changes", "/solutions#changes"), current("Find Affected Products & Lots", "/solutions#affected"), current("Investigate Supplier Issues", "/solutions#supplier"), current("Connect Fragmented Evidence", "/solutions#evidence"), current("Challenge Suspected Root Causes", "/solutions#challenge"), current("Identify Missing Evidence", "/solutions#unknowns")] },
    { title: "By Role", items: [current("Quality Leaders", "/solutions#quality-leaders", "See the full investigation picture."), current("Investigators / QA", "/solutions#investigators", "Move from signal to evidence."), current("Regulatory Affairs", "/solutions#regulatory", "Prepare traceable review context."), current("Product / R&D", "/solutions#product", "Connect changes to outcomes."), current("Supplier Quality", "/solutions#supplier-quality", "Follow supplier and component relationships."), current("Manufacturing Quality", "/solutions#manufacturing", "Understand affected lots and changes."), current("Executives", "/solutions#executives", "Review decision-ready assurance.")] },
    { title: "By Investigation", items: [current("Complaint Investigation", "/solutions#complaint-investigation"), current("ProductVersion Investigation", "/solutions#version-investigation"), current("Change Investigation", "/solutions#change-investigation"), current("Supplier Investigation", "/solutions#supplier-investigation"), current("Component Investigation", "/solutions#component-investigation"), current("Lot / Batch Investigation", "/solutions#lot-investigation"), current("Risk & Failure Investigation", "/solutions#risk-investigation"), current("Cross-System Investigation", "/solutions#cross-system")] },
    { title: "Investigate with MDARIX", items: [current("Why did complaints increase after Rev D?", "/platform/investigation", "Follow a signal through product version, change, component, supplier, lots, evidence, hypotheses, unknowns, assurance, and human decision.")] },
  ],
  "Product Lifecycle": [
    { title: "Discover & Define", items: [future("Product Strategy", "strategy"), future("User / Clinical Need", "clinical-need"), future("Product Requirements", "requirements")] },
    { title: "Develop & Prove", items: [future("Design & Development", "design"), future("Design Controls", "design-controls"), future("Verification & Validation", "verification"), future("Clinical Intelligence", "clinical"), future("Regulatory Intelligence", "regulatory")] },
    { title: "Build & Release", items: [future("Manufacturing Intelligence", "manufacturing"), current("Supplier Intelligence", "/platform/supplier-intelligence"), current("Component Intelligence", "/platform/component-intelligence"), current("Lot / Batch Intelligence", "/platform/lot-batch-intelligence"), current("Change Intelligence", "/platform/change-intelligence")] },
    { title: "Monitor, Improve & Evolve", items: [current("Complaint Intelligence", "/solutions#complaints"), current("Post-Market Investigation", "/platform/investigation"), future("Signal Intelligence", "signal"), current("Evidence Intelligence", "/platform/evidence"), future("CAPA Intelligence", "capa"), future("Field Action / Recall Intelligence", "recall"), current("Product Change Intelligence", "/platform/timeline"), future("Continuous Monitoring", "monitoring"), future("Product Retirement", "retirement")] },
  ],
  Trust: [
    { title: "A Different Intelligence Layer", items: [current("Not Another QMS", "/why-mdarix#not-qms", "Keep existing systems of record."), current("Product Reality", "/why-mdarix#product-reality", "Understand relationships across lifecycle information."), current("Investigation Intelligence", "/why-mdarix#investigation", "Investigate across connected context."), current("Evidence Before Inference", "/why-mdarix#evidence", "Separate facts, interpretations, hypotheses, and decisions.")] },
    { title: "Trustworthy Investigation", items: [current("Challenge the Explanation", "/why-mdarix#challenge"), current("AI You Can Inspect", "/why-mdarix#inspectable-ai"), current("Humans Decide", "/why-mdarix#humans-decide")] },
    { title: "Questions MDARIX Helps Explore", items: [current("What changed before the signal?", "/solutions#changes"), current("Which versions and lots are affected?", "/solutions#affected"), current("What evidence contradicts the cause?", "/solutions#challenge"), current("What information is still missing?", "/solutions#unknowns")] },
    { title: "Trust Foundations", items: [current("AI Assurance", "/platform/ai-assurance"), current("Security & Access", "/security"), current("Plans & Entitlements", "/plans"), current("Integration Approach", "/integrations")] },
  ],
  Company: [
    { title: "Company", items: [current("Why MDARIX", "/why-mdarix", "Evidence-first investigation intelligence for medical-device teams."), current("Our approach", "/company", "A governed intelligence layer above existing systems of record."), current("Contact", "/request-demo", "Discuss your investigation workflow with MDARIX.")] },
    { title: "Trust", items: [current("Security & access", "/security"), current("AI assurance", "/ai-trust"), current("Integration approach", "/integrations")] },
  ],
};

// Keep the lifecycle menu distinct from the platform's generic investigation pages.
const lifecycleMonitorGroup = menus["Product Lifecycle"].find((group) => group.title === "Monitor, Improve & Evolve");
if (lifecycleMonitorGroup) {
  lifecycleMonitorGroup.items = lifecycleMonitorGroup.items.map((item) =>
    item.label === "Post-Market Investigation"
      ? current(item.label, "/platform/post-market-surveillance")
      : item.label === "Evidence Intelligence"
        ? current(item.label, "/platform/lifecycle-evidence-intelligence")
        : item,
  );
}

const pages: Record<string, { eyebrow: string; title: string; copy: string }> = {
  "/": { eyebrow: "Product investigation intelligence for medical devices", title: "Turn post-market signals into defensible product decisions.", copy: "Connect complaints, product context, lifecycle evidence, risk, and human review in one governed investigation story." },
  "/platform": { eyebrow: "Platform & AI", title: "A connected intelligence layer for product investigation.", copy: "Reconstruct product reality, investigate competing explanations, expose contradictions and unknowns, and preserve traceable human decisions." },
  "/solutions": { eyebrow: "Solutions", title: "Start with the question your team needs to answer.", copy: "Investigate complaint increases, product changes, affected lots, supplier issues, fragmented evidence, suspected causes, and missing information across systems." },
  "/product-lifecycle": { eyebrow: "Product lifecycle", title: "Intelligence from product definition through post-market evolution.", copy: "Current investigation capabilities anchor a broader lifecycle vision. Future areas are identified clearly without implying working functionality." },
  "/why-mdarix": { eyebrow: "Why MDARIX", title: "Evidence before inference. Challenge before conclusion.", copy: "MDARIX works above your existing systems of record to reconstruct product reality and make investigation intelligence inspectable." },
  "/resources": { eyebrow: "Resources", title: "Explore product investigation intelligence.", copy: "Learn how MDARIX connects product reality, evidence, temporal context, investigation, decisions, assurance, and governance." },
  "/plans": { eyebrow: "Plans", title: "Start with Free Early Access.", copy: "Create an account, verify your email, and enter a tenant-scoped development workspace. Future commercial packaging is not represented here." },
  "/pricing": { eyebrow: "Pricing", title: "Choose the investigation foundation that fits your team.", copy: "Compare illustrative early-access options for connected product context, evidence intelligence, assurance, and governed human decisions." },
  "/capabilities": { eyebrow: "Current capabilities", title: "From connected lifecycle data to traceable decisions.", copy: "Explore the current product reality, investigation, evidence, challenge, decision, assurance, and governance capabilities." },
  "/roadmap": { eyebrow: "Product roadmap", title: "Current capabilities and the broader lifecycle direction.", copy: "Future roadmap areas are informational and do not represent available workflows or committed release dates." },
  "/integrations": { eyebrow: "Integrations", title: "Work above the systems you already trust.", copy: "QMS, PLM, ERP, MES, supplier, document, and evidence platforms remain authoritative systems of record." },
  "/security": { eyebrow: "Security & access", title: "Controlled, tenant-scoped, and traceable by design.", copy: "Authentication, role and field authorization, action controls, provenance, and human authority form the current security foundation. Independent certification is not claimed." },
  "/ai-trust": { eyebrow: "AI trust", title: "Grounded intelligence with visible limits.", copy: "MDARIX preserves evidence references, temporal context, contradictions, unknowns, provenance, and human review. AI does not create the final regulated decision." },
  "/request-demo": { eyebrow: "Get started", title: "Explore MDARIX in your lifecycle context.", copy: "Create an account, verify your email, sign in, and enter the tenant-scoped application." },
  "/company": { eyebrow: "Company", title: "A more defensible way to investigate product reality.", copy: "MDARIX is designed for medical-device teams that need connected evidence, visible uncertainty, and accountable human decisions." },
};

const lifecycleContent: Record<string, { eyebrow: string; title: string; copy: string }> = {
  strategy: { eyebrow: "Product lifecycle · Discover", title: "Turn market and patient needs into a governed product direction.", copy: "Frame the intended use, target users, clinical problem, market need, business goals, and regulatory pathway before detailed design work begins." },
  "clinical-need": { eyebrow: "Product lifecycle · Discover", title: "Define the clinical need and the outcome the device must support.", copy: "Connect user needs, patient populations, care settings, clinical risks, and measurable outcomes so product requirements begin with a clear clinical purpose." },
  requirements: { eyebrow: "Product lifecycle · Define", title: "Translate user needs into traceable product requirements.", copy: "Establish functional, safety, performance, usability, software, security, and regulatory requirements with ownership, rationale, and verification intent." },
  design: { eyebrow: "Product lifecycle · Develop", title: "Manage design decisions with evidence attached to every requirement.", copy: "Coordinate design outputs, interfaces, risk controls, configuration decisions, and revisions while preserving traceability from requirement to implementation." },
  "design-controls": { eyebrow: "Product lifecycle · Develop", title: "Make design controls visible from planning through release.", copy: "Organize design inputs, outputs, reviews, verification, validation, change control, and approval evidence into a reviewable design history." },
  verification: { eyebrow: "Product lifecycle · Prove", title: "Show that the design meets its specified requirements.", copy: "Bring test protocols, results, deviations, failures, corrective actions, and approval records together so verification status is inspectable and complete." },
  clinical: { eyebrow: "Product lifecycle · Prove", title: "Connect clinical evidence to product decisions.", copy: "Maintain the relationship between clinical evaluation, intended use, benefit-risk reasoning, usability evidence, and the product configuration under review." },
  regulatory: { eyebrow: "Product lifecycle · Release", title: "Prepare a traceable regulatory evidence story.", copy: "Organize submissions, commitments, standards, approvals, findings, and market-specific obligations around the exact product version and evidence scope." },
  manufacturing: { eyebrow: "Product lifecycle · Build", title: "Connect released design intent to manufacturing reality.", copy: "Relate manufacturing processes, suppliers, components, lots, deviations, inspections, and release records back to the approved product configuration." },
  signal: { eyebrow: "Product lifecycle · Monitor", title: "Detect and investigate signals across the installed product base.", copy: "Combine complaints, service data, adverse events, returns, trends, and product-version context to distinguish emerging signals from isolated observations." },
  capa: { eyebrow: "Product lifecycle · Improve", title: "Move from a confirmed issue to controlled improvement.", copy: "Link investigation findings to containment, root-cause analysis, corrective and preventive actions, effectiveness checks, owners, and approval evidence." },
  recall: { eyebrow: "Product lifecycle · Act", title: "Coordinate field action decisions with complete product scope.", copy: "Identify affected versions, lots, markets, customers, risk rationale, communications, execution status, and evidence for a controlled field action." },
  monitoring: { eyebrow: "Product lifecycle · Monitor", title: "Continuously watch product performance and evidence quality.", copy: "Track trends, thresholds, open unknowns, supplier performance, complaint patterns, and changes that may alter the product risk picture." },
  retirement: { eyebrow: "Product lifecycle · Evolve", title: "Retire products with traceability and accountability.", copy: "Preserve the final configuration, support obligations, residual risks, records, customer impact, and regulatory responsibilities through product retirement." },
  "supplier-intelligence": { eyebrow: "Product lifecycle · Build & Release", title: "Understand supplier connections behind product signals.", copy: "A product issue may involve a component, material, supplier, or supplier change. MDARIX helps teams connect supplier and component information with product records and emerging signals, supporting clearer investigations and impact assessments." },
  "component-intelligence": { eyebrow: "Product lifecycle · Build & Release", title: "See how component relationships affect product decisions.", copy: "Components connect product design, suppliers, manufacturing, risk, and field performance. MDARIX helps teams see these relationships in context, making it easier to assess whether a component-related issue may affect other products or versions." },
  "lot-batch-intelligence": { eyebrow: "Product lifecycle · Build & Release", title: "Assess lot and batch context when investigating product signals.", copy: "Lot and batch information can help teams assess the scope and distribution of a potential issue. MDARIX connects lot context with product, manufacturing, supplier, and post-market records to support structured investigation and impact review." },
  "change-intelligence": { eyebrow: "Product lifecycle · Build & Release", title: "Understand the product impact of every change.", copy: "Changes to design, components, suppliers, processes, labeling, or software can affect requirements, risks, evidence, and products in the field. MDARIX helps teams connect change proposals to those relationships so impact assessments are supported by product context." },
};

Object.assign(lifecycleContent, {
  "post-market-surveillance": { eyebrow: "Product lifecycle · Monitor, Improve & Evolve", title: "Turn post-market information into connected product insight.", copy: "Post-market surveillance brings together complaints, adverse events, service information, returns, trends, and other field evidence. MDARIX connects this information to products, versions, lots, risks, investigations, and decisions so teams can review emerging signals in context." },
  "lifecycle-evidence-intelligence": { eyebrow: "Product lifecycle · Monitor, Improve & Evolve", title: "Make lifecycle evidence easier to find, connect, and evaluate.", copy: "Evidence is most useful when reviewers can see the product question, risk, investigation, or decision it supports. MDARIX preserves source, version, date, provenance, contradictions, limitations, and missing links across the lifecycle." },
});

const anchorPages: Record<string, { eyebrow: string; title: string; copy: string }> = {
  complaints: { eyebrow: "Solution · Complaint signals", title: "Find out what changed before complaints increased.", copy: "Connect complaint patterns to product versions, changes, components, suppliers, lots, and evidence so investigators can separate a signal from a conclusion." },
  changes: { eyebrow: "Solution · Product changes", title: "Understand the changes that shaped the signal.", copy: "Compare product revisions and controlled changes with complaint timing, affected lots, configuration, and supporting evidence." },
  affected: { eyebrow: "Solution · Affected products and lots", title: "Trace impact from version to lot.", copy: "Follow product versions, component relationships, suppliers, and lot context to identify what is affected and what remains unknown." },
  supplier: { eyebrow: "Solution · Supplier investigation", title: "Connect supplier context to product reality.", copy: "Bring supplier, component, change, lot, and complaint relationships into one investigation workspace." },
  evidence: { eyebrow: "Solution · Evidence intelligence", title: "Make evidence visible before inference.", copy: "Review source anchors, reliability, temporal context, contradictions, and missing evidence before forming a hypothesis." },
  challenge: { eyebrow: "Solution · AI Challenger", title: "Challenge the explanation before it becomes a conclusion.", copy: "Expose competing hypotheses, contradictions, unknowns, and limitations so authorized humans can review the reasoning." },
  unknowns: { eyebrow: "Solution · Unknowns radar", title: "See what the investigation still cannot establish.", copy: "Surface incomplete traceability, missing lot references, unsupported failure chains, and other evidence gaps." },
  "quality-leaders": { eyebrow: "Role · Quality leaders", title: "Give quality leaders the full investigation picture.", copy: "Review product reality, evidence quality, competing explanations, assurance, and human decisions in one governed view." },
  investigators: { eyebrow: "Role · Investigators / QA", title: "Move from signal to evidence with confidence.", copy: "Build a traceable investigation across product, change, supplier, lot, complaint, evidence, and hypothesis context." },
  regulatory: { eyebrow: "Role · Regulatory affairs", title: "Prepare traceable review context.", copy: "Preserve provenance, limitations, temporal context, and human review boundaries for regulated investigation workflows." },
  product: { eyebrow: "Role · Product and R&D", title: "Connect product changes to outcomes.", copy: "Understand how revisions, components, configuration, and lifecycle events relate to downstream signals." },
  "supplier-quality": { eyebrow: "Role · Supplier quality", title: "Follow supplier and component relationships.", copy: "Investigate supplier-linked signals with affected lots, component revisions, evidence, and missing context in view." },
  manufacturing: { eyebrow: "Role · Manufacturing quality", title: "Understand affected lots and changes.", copy: "Connect manufacturing context to product versions, lots, complaints, evidence, and investigation decisions." },
  executives: { eyebrow: "Role · Executives", title: "Review decision-ready assurance.", copy: "See what is known, what is challenged, what remains unresolved, and where human authorization is required." },
};

const solutionOverrides: Record<string, { eyebrow: string; title: string; copy: string }> = {
  complaints: { eyebrow: "Solution · Complaint signals", title: "Understand what is driving an increase in complaints.", copy: "A rise in complaints may relate to a product version, component, supplier, lot, market, or change. MDARIX helps teams review these connections in context, explore possible patterns, and document the evidence behind their assessment." },
  changes: { eyebrow: "Solution · Product changes", title: "See how product changes relate to field experience.", copy: "Design, component, supplier, software, and manufacturing changes can affect products already in use. MDARIX connects change history with product context and post-market signals to help teams assess possible relationships." },
  affected: { eyebrow: "Solution · Affected products and lots", title: "Map potential impact across products and lots.", copy: "When an issue is identified, teams need to understand which products, versions, configurations, or lots may be involved. MDARIX connects these records to organize scope assessment and review supporting relationships." },
  supplier: { eyebrow: "Solution · Supplier investigation", title: "Follow supplier relationships through to product impact.", copy: "Supplier-related issues can affect multiple components, products, and lots. MDARIX connects supplier records with product and post-market context to support a complete review of potential impact." },
  evidence: { eyebrow: "Solution · Evidence intelligence", title: "Bring scattered evidence into the decision context.", copy: "Relevant information can be spread across quality, regulatory, product, supplier, and manufacturing systems. MDARIX connects available records to the issue under review and makes missing evidence visible." },
  challenge: { eyebrow: "Solution · AI Challenger", title: "Test suspected causes against connected evidence.", copy: "A plausible cause should be evaluated against available facts and alternative explanations. MDARIX organizes hypotheses, supporting or conflicting evidence, and uncertainty before a conclusion." },
  unknowns: { eyebrow: "Solution · Unknowns radar", title: "Make evidence gaps visible before decisions are finalized.", copy: "MDARIX identifies missing, outdated, or conflicting evidence links so reviewers understand what is known, what remains uncertain, and what still needs attention." },
};

const pricingPlans = [
  { name: "Free", price: "$0", cadence: "forever", note: "Explore the connected investigation workspace.", features: ["1 workspace", "Up to 3 users", "Product 360 and investigation basics", "Community guidance"], action: "Start free" },
  { name: "Individual", price: "$49", cadence: "per user / month", note: "For focused quality and investigation work.", features: ["1 workspace", "Up to 10 users", "Evidence and hypothesis intelligence", "Standard support"], action: "Choose Individual" },
  { name: "Pro", price: "$149", cadence: "per user / month", note: "For teams connecting evidence across functions.", features: ["Unlimited workspaces", "Up to 50 users", "AI assurance and decision workflows", "Priority support"], action: "Choose Pro", featured: true },
  { name: "Enterprise", price: "Custom", cadence: "annual plan", note: "For governed, tenant-scoped deployment at scale.", features: ["Advanced administration", "SSO and enterprise access", "Custom integrations", "Dedicated success support"], action: "Talk to us" },
];

const platformCapabilityData: Record<string, { kicker: string; summary: string; stats: string[]; cards: { title: string; text: string }[]; steps: string[] }> = {
  "product-360": { kicker: "Product intelligence", summary: "A decision-ready view of the product as it exists across configuration, versions, suppliers, lots, complaints, evidence, and lifecycle events.", stats: ["4 components", "7 lots", "11 complaints", "12 lifecycle events"], cards: [{ title: "Configuration at a glance", text: "See active components, revisions, suppliers, and status in one product context." }, { title: "Impact you can trace", text: "Move from a complaint to affected lots and product versions without losing the source relationship." }, { title: "Limitations stay visible", text: "Incomplete traceability, missing lot references, and unsupported conclusions remain explicit." }], steps: ["Product", "Versions", "Configuration", "Lots", "Complaints", "Evidence"] },
  "reality-graph": { kicker: "Relationship intelligence", summary: "Connect the entities that shape an investigation so teams can follow a signal through product reality instead of relying on disconnected lists.", stats: ["Products", "Components", "Suppliers", "Evidence links"], cards: [{ title: "Relationship-first", text: "Follow product, component, supplier, lot, change, complaint, and evidence relationships." }, { title: "Context before causality", text: "A graph path is evidence context—not an automatic root-cause conclusion." }, { title: "Find the gaps", text: "See missing links and partial traceability before they become hidden assumptions." }], steps: ["Signal", "Product", "Component", "Supplier", "Lot", "Evidence"] },
  "product-version": { kicker: "ProductVersion intelligence", summary: "Compare versions with temporal discipline: what changed, what was effective, what was recorded, and what was known at each point in the investigation.", stats: ["Rev A", "Rev B", "Rev C", "Rev D"], cards: [{ title: "Version-aware scope", text: "Keep product identity distinct from its version and preserve the selected scope through the workflow." }, { title: "Change context", text: "Relate revision changes to components, complaints, affected lots, and evidence." }, { title: "Temporal clarity", text: "Separate current, event-as-of, and known-as-of views so historical context is not rewritten." }], steps: ["Product", "Rev A", "Rev B", "Rev C", "Rev D", "Impact"] },
  timeline: { kicker: "Timeline intelligence", summary: "Reconstruct the sequence around a signal and make the difference between effective, recorded, and known dates clear to every reviewer.", stats: ["12 events", "3 date modes", "6 changes", "4 revisions"], cards: [{ title: "See the sequence", text: "Place product, design, change, supplier, complaint, and evidence events on one readable timeline." }, { title: "Three views of time", text: "Switch between current, event-as-of, and known-as-of context without mixing their meaning." }, { title: "Review what changed", text: "Use the timeline as an investigation starting point, with provenance and limitations attached." }], steps: ["Effective", "Recorded", "Known", "Change", "Signal", "Review"] },
  "post-market-surveillance": { kicker: "Post-market surveillance", summary: "Connect complaints, adverse events, service information, returns, trends, and field evidence to the products, versions, lots, risks, investigations, and decisions they inform.", stats: ["Complaints", "Field signals", "Product scope", "Review actions"], cards: [{ title: "Connect field information", text: "Bring post-market records together with product, version, lot, component, supplier, and manufacturing context." }, { title: "Review emerging signals", text: "Explore patterns over time while keeping source records, limitations, and review rationale visible." }, { title: "Support governed action", text: "Link surveillance findings to investigations, risk review, CAPA, field action assessment, and human decisions." }], steps: ["Field data", "Product context", "Signal", "Investigation", "Assessment", "Action"] },
  "lifecycle-evidence-intelligence": { kicker: "Evidence intelligence", summary: "Make lifecycle evidence easier to find, connect, and evaluate by preserving its source, version, date, provenance, contradictions, limitations, and missing links.", stats: ["Sources", "Provenance", "Evidence gaps", "Decisions"], cards: [{ title: "Keep evidence in context", text: "Link evidence to products, requirements, risks, investigations, changes, claims, assessments, and decisions." }, { title: "Expose limitations", text: "Make missing, outdated, conflicting, or weak evidence relationships visible before review conclusions are formed." }, { title: "Preserve the decision trail", text: "Show which evidence supported an assessment and retain the human review boundary around the decision." }], steps: ["Source", "Context", "Evidence", "Gap", "Review", "Decision"] }
};

const capabilityStory = (slug: string, title: string) => {
  const investigation = ["ask-mdarix", "investigation", "evidence", "hypotheses", "challenger", "unknowns"].includes(slug);
  const decision = ["failure-chain", "counterfactual", "decision-center", "investigation-brief"].includes(slug);
  const trust = ["ai-assurance", "ai-provenance", "human-review", "audit-trail", "enterprise-administration"].includes(slug);
  const lifecycle = !investigation && !decision && !trust;
  const kicker = investigation ? "Investigation intelligence" : decision ? "Decision intelligence" : trust ? "Trust & governance" : "Product lifecycle intelligence";
  const lens = investigation ? "signal, evidence, competing explanations, and unknowns" : decision ? "evidence, limitations, review, and an authorized human decision" : trust ? "identity, provenance, assurance, and governed human authority" : "product intent, development evidence, release context, and post-market learning";
  return { kicker, summary: `${title} helps teams move through an inspectable E2E workflow across ${lens}. Every step keeps source context, scope, limitations, and responsibility visible.`, stats: investigation ? ["Signal", "Evidence", "Hypotheses", "Unknowns"] : decision ? ["Context", "Challenge", "Review", "Decision"] : trust ? ["Identity", "Provenance", "Assurance", "Audit"] : ["Define", "Develop", "Release", "Improve"], cards: [{ title: "Start with context", text: `Bring the relevant ${lens} into one reviewable workspace without losing the source boundary.` }, { title: "Inspect before inference", text: "Separate observed facts from interpretation, uncertainty, recommendations, and conclusions." }, { title: "Close the loop", text: "Preserve limitations, reviewer responsibility, and the traceable next action at the end of the journey." }], steps: investigation ? ["Question", "Scope", "Evidence", "Challenge", "Unknowns", "Review"] : decision ? ["Context", "Analysis", "Challenge", "Readiness", "Human", "Decision"] : trust ? ["Identity", "Access", "Evidence", "Assurance", "Review", "Audit"] : ["Define", "Develop", "Prove", "Release", "Monitor", "Improve"] };
};

function PublicFooter() {
  const columns = [
    { title: "About MDARIX", links: [["Our mission", "/why-mdarix"], ["Trust & security", "/security"], ["Resources", "/resources"], ["Contact us", "/request-demo"]] },
    { title: "Platform", links: [["Product 360", "/platform/product-360"], ["Investigation intelligence", "/platform/investigation"], ["Evidence intelligence", "/platform/evidence"], ["AI assurance", "/platform/ai-assurance"]] },
    { title: "Solutions", links: [["Complaint investigation", "/solutions#complaint-investigation"], ["Product change investigation", "/solutions#change-investigation"], ["Supplier investigation", "/solutions#supplier-investigation"], ["Affected lots", "/solutions#affected"]] },
    { title: "Use cases", links: [["Quality leaders", "/solutions#quality-leaders"], ["Investigators / QA", "/solutions#investigators"], ["Regulatory affairs", "/solutions#regulatory"], ["Supplier quality", "/solutions#supplier-quality"]] },
    { title: "Resources", links: [["Investigation playbooks", "/resources"], ["Lifecycle intelligence", "/product-lifecycle"], ["Roadmap", "/roadmap"], ["Pricing", "/pricing"]] },
    { title: "Connect", links: [["Integration approach", "/integrations"], ["Security & access", "/security"], ["Request a demo", "/request-demo"], ["Sign in", "/signin"]] },
  ];
  return <footer className="public-footer public-footer-expanded"><div className="public-footer-grid">{columns.map(column => <section key={column.title}><h3>{column.title}</h3>{column.links.map(([label, href]) => <a key={label} href={href}>{label}</a>)}</section>)}</div><div className="public-footer-bottom"><span>MDARIX — System of Intelligence, not System of Record.</span><span>Evidence before inference · Humans decide</span></div></footer>;
}

export function PublicMegaSite({ path }: { path: string }) {
  const [openMenu, setOpenMenu] = useState<string | null>(null); const [mobileOpen, setMobileOpen] = useState(false); const [hash, setHash] = useState(() => window.location.hash.slice(1));
  useEffect(() => { const close = (event: KeyboardEvent) => { if (event.key === "Escape") { setOpenMenu(null); setMobileOpen(false); } }; window.addEventListener("keydown", close); return () => window.removeEventListener("keydown", close); }, []);
  useEffect(() => { const update = () => setHash(window.location.hash.slice(1)); window.addEventListener("hashchange", update); return () => window.removeEventListener("hashchange", update); }, [path]);
  useEffect(() => { const closeAfterMenuLink = (event: MouseEvent) => { if ((event.target as HTMLElement).closest(".mega-menu a")) { setOpenMenu(null); setMobileOpen(false); } }; document.addEventListener("click", closeAfterMenuLink); return () => document.removeEventListener("click", closeAfterMenuLink); }, []);
  const capability = path.startsWith("/platform/") ? (path.split("/").pop() ?? "capability").replace(/-/g, " ").replace(/\b\w/g, letter => letter.toUpperCase()) : null;
  const capabilitySlug = path.split("/").pop() ?? "capability";
  const roadmapTarget = path === "/roadmap" && window.location.hash ? window.location.hash.slice(1).replace(/-/g, " ").replace(/\b\w/g, letter => letter.toUpperCase()) : null;
  const anchorPage = anchorPages[hash];
  const lifecyclePage = lifecycleContent[capabilitySlug];
  const solutionPage = solutionOverrides[hash];
  const page = roadmapTarget ? { eyebrow: "Future", title: roadmapTarget, copy: "Planned as part of the broader MDARIX Medical Device Product Lifecycle Intelligence platform. This page is informational and does not represent available functionality." } : solutionPage ?? anchorPage ?? lifecyclePage ?? (capability ? { eyebrow: "Current capability", title: capability, copy: `${capability} contributes to the connected MDARIX product-investigation workflow across product, version, temporal, evidence, tenant, and human-governance boundaries.` } : pages[path] ?? pages["/"]);
  const questionFlow = ["Complaint signal", "ProductVersion", "Change", "Component", "Supplier", "Affected lots", "Evidence", "Hypotheses", "Contradictions", "Unknowns", "Assurance", "Human decision"];
  const isHome = path === "/";
  const platformCapability = capability ? (platformCapabilityData[capabilitySlug] ?? capabilityStory(capabilitySlug, page.title)) : null;
  const closeMenuAndNavigate = () => { setOpenMenu(null); setMobileOpen(false); window.setTimeout(() => window.scrollTo({ top: 0, behavior: "smooth" }), 0); };
  if (typeof document !== "undefined") document.documentElement.dataset.publicPath = path;
  return <div className="public-shell" onClick={() => openMenu && setOpenMenu(null)}><header className="public-header" onClick={event => event.stopPropagation()}><a className="brand" href="/" aria-label="MDARIX home">MDARIX<span>Product intelligence</span></a><button className="mobile-menu-button" aria-expanded={mobileOpen} aria-controls="public-navigation" onClick={() => setMobileOpen(!mobileOpen)}>Menu</button><nav id="public-navigation" className={mobileOpen ? "mobile-open" : ""}>{Object.keys(menus).map(name => <button key={name} aria-expanded={openMenu === name} onClick={() => setOpenMenu(openMenu === name ? null : name)}>{name}</button>)}<a href="/resources" onClick={closeMenuAndNavigate}>Resources</a><a href="/pricing" onClick={closeMenuAndNavigate}>Pricing</a></nav><div className="public-actions"><a href="/signin">Login</a><a className="primary-action" href="/request-demo">Request demo</a></div>{openMenu && <div className="mega-menu" role="region" aria-label={`${openMenu} menu`}>{menus[openMenu].map(group => <section key={group.title}><h2>{group.title}</h2>{group.items.map(entry => <a key={entry.label} href={entry.href} onClick={closeMenuAndNavigate}><span><strong>{entry.label}</strong>{entry.description && <em>{entry.description}</em>}</span>{entry.future && <small className="status-future">Future</small>}</a>)}</section>)}</div>}</header>
    <main className="public-main"><section className="public-hero"><span className="eyebrow">{page.eyebrow}</span><h1>{page.title}</h1><p>{page.copy}</p><div className="public-cta"><a className="primary-action" href="/platform">Explore the platform</a><a className="secondary-link" href="/signup">Get started →</a></div></section>
      <section className="public-question"><span className="eyebrow">A product investigation question</span><h2>Why did shutdown complaints increase after Product Rev D?</h2><p>MDARIX helps teams follow the question across product reality, evidence, uncertainty, assurance, and controlled human decision-making.</p><div className="question-flow">{questionFlow.map((step, index) => <React.Fragment key={step}><article>{step}</article>{index < questionFlow.length - 1 && <ChevronRight aria-hidden="true" />}</React.Fragment>)}</div></section>
      <section className="public-story"><div><span className="eyebrow">A different intelligence layer</span><h2>Keep your systems of record. Connect the investigation.</h2></div><div className="story-grid"><article><strong>Product reality</strong><p>Relate products, versions, components, suppliers, lots, changes, complaints, risks, and evidence.</p></article><article><strong>Evidence before inference</strong><p>Separate observations, interpretations, hypotheses, contradictions, unknowns, and decisions.</p></article><article><strong>AI you can inspect</strong><p>Show grounding, temporal context, ProductVersion validation, provenance, and limitations.</p></article><article><strong>Humans decide</strong><p>AI supports investigation. Authorized humans make controlled decisions.</p></article></div></section>
      {isHome && <section className="medtech-editorial"><div><span className="eyebrow">Built for MedTech investigation teams</span><h2>Bring quality, regulatory, product, supplier, and manufacturing context into one review.</h2><p>MDARIX helps cross-functional teams inspect the same product reality while preserving source ownership, evidence provenance, uncertainty, and accountable human decisions.</p><a className="secondary-link" href="/solutions">Explore MedTech workflows →</a></div><figure><img src="/medtech-investigation-team.png" alt="Medical-device quality, regulatory, and engineering professionals reviewing a connected device investigation"/><figcaption>Connected review across product evidence and post-market signals.</figcaption></figure></section>}
      {path === "/roadmap" && !roadmapTarget && <section className="public-story roadmap-grid"><article><h2>Current capabilities</h2><p>Product 360, Reality Graph, temporal context, evidence intelligence, investigation, hypotheses, challenger, unknowns, failure chain, counterfactuals, decisions, assurance, and governance foundations.</p></article><article><span className="status-future">Future</span><h2>Broader lifecycle intelligence</h2><p>Strategy, requirements, design controls, regulatory, clinical, manufacturing operations, CAPA, recall, continuous monitoring, and retirement remain roadmap areas.</p></article></section>}
      {(path === "/plans" || path === "/pricing") && <section className="pricing-section"><p className="pricing-disclaimer">Illustrative early-access pricing. Plans and billing are not yet enabled.</p><div className="pricing-grid">{pricingPlans.map(plan => <article className={`pricing-card ${plan.featured ? "pricing-card-featured" : ""}`} key={plan.name}>{plan.featured && <span className="pricing-badge">Most popular</span>}<h2>{plan.name}</h2><p>{plan.note}</p><div className="pricing-price">{plan.price}</div><small>{plan.cadence}</small><ul>{plan.features.map(feature => <li key={feature}>{feature}</li>)}</ul><a className={plan.featured ? "primary-action" : "secondary-action"} href={plan.name === "Enterprise" ? "/request-demo" : "/signup"}>{plan.action}</a></article>)}</div></section>}
      {platformCapability && <section className="capability-detail"><div className="capability-intro"><div><span className="eyebrow">{platformCapability.kicker}</span><h2>{page.title}</h2><p>{platformCapability.summary}</p></div><div className="capability-visual" aria-label={`${page.title} illustration`}><div className="visual-orbit orbit-one"/><div className="visual-orbit orbit-two"/><div className="visual-node node-one">{platformCapability.steps[0]}</div><div className="visual-node node-two">{platformCapability.steps[2]}</div><div className="visual-node node-three">{platformCapability.steps[5]}</div></div></div><div className="capability-stats">{platformCapability.stats.map(stat => <strong key={stat}>{stat}</strong>)}</div><div className="capability-cards">{platformCapability.cards.map(card => <article key={card.title}><span className="capability-index">0{platformCapability.cards.indexOf(card) + 1}</span><h3>{card.title}</h3><p>{card.text}</p></article>)}</div><div className="capability-journey"><span className="eyebrow">How the story connects</span><div>{platformCapability.steps.map((step, index) => <React.Fragment key={step}><span>{step}</span>{index < platformCapability.steps.length - 1 && <ChevronRight aria-hidden="true"/>}</React.Fragment>)}</div></div></section>}
      {anchorPage && <section className="solution-detail"><div><span className="eyebrow">End-to-end solution story</span><h2>{page.title}</h2><p>{page.copy}</p></div><div className="solution-flow"><article><span>01</span><h3>Frame the question</h3><p>Define the signal, scope, time window, and accountable review team.</p></article><article><span>02</span><h3>Connect the context</h3><p>Bring product, version, change, supplier, lot, complaint, and evidence context together.</p></article><article><span>03</span><h3>Inspect the uncertainty</h3><p>Separate what is observed from what is inferred, contradicted, missing, or still unknown.</p></article><article><span>04</span><h3>Move to governed action</h3><p>Preserve provenance and limitations while authorized humans review and decide.</p></article></div><div className="solution-visual"><span>Signal</span><b>→</b><span>Context</span><b>→</b><span>Evidence</span><b>→</b><span>Review</span><b>→</b><strong>Decision</strong></div></section>}
      {path === "/resources" && <section className="resource-detail"><span className="eyebrow">Resource library</span><h2>Practical guidance for every investigation stage.</h2><p>Use these resources to move from a product signal to a traceable, reviewable decision while keeping evidence, uncertainty, and human authority visible.</p><div className="resource-grid"><article><strong>Investigation playbooks</strong><p>Complaint increases, product changes, supplier issues, affected lots, and missing evidence.</p><a href="/solutions#complaints" onClick={closeMenuAndNavigate}>Explore playbooks →</a></article><article><strong>Trust &amp; governance guides</strong><p>AI assurance, provenance, role boundaries, audit trails, and controlled human review.</p><a href="/platform/ai-assurance" onClick={closeMenuAndNavigate}>Review trust controls →</a></article><article><strong>Lifecycle perspectives</strong><p>Discover, develop, prove, release, monitor, improve, and evolve with connected context.</p><a href="/product-lifecycle" onClick={closeMenuAndNavigate}>Explore lifecycle →</a></article></div></section>}
    </main><PublicFooter /></div>;
}
