import React, { useEffect, useState } from "react";
import { ChevronRight } from "lucide-react";

type MenuItem = { label: string; href: string; future?: boolean; description?: string };
type MenuGroup = { title: string; items: MenuItem[] };
const current = (label: string, href: string, description?: string): MenuItem => ({ label, href, description });
const future = (label: string, anchor: string): MenuItem => ({ label, href: `/roadmap#${anchor}`, future: true });

const menus: Record<string, MenuGroup[]> = {
  "Platform & AI": [
    { title: "Product Intelligence", items: [current("Product 360", "/platform/product-360", "See product, version, configuration, and lifecycle context."), current("Product Reality Graph", "/platform/reality-graph", "Connect product, supplier, lot, complaint, change, and evidence relationships."), current("ProductVersion Intelligence", "/platform/product-360"), current("Timeline Intelligence", "/platform/timeline")] },
    { title: "Investigation Intelligence", items: [future("Ask MDARIX", "ask-mdarix"), current("Investigation Workspace", "/platform/investigation"), current("Evidence Intelligence", "/platform/evidence"), current("Hypothesis Intelligence", "/platform/hypotheses"), current("AI Challenger", "/platform/challenger"), current("Unknowns Radar", "/platform/unknowns")] },
    { title: "Decision Intelligence", items: [current("Failure Chain Intelligence", "/platform/failure-chain"), current("Counterfactual Analysis", "/platform/counterfactual"), current("Decision Center", "/platform/decision-center"), current("Investigation Brief", "/platform/investigation-brief")] },
    { title: "Trust & Governance", items: [current("AI Assurance", "/platform/ai-assurance"), current("AI Provenance", "/ai-trust"), current("Human Review & Approval", "/platform/human-review"), current("Audit Trail", "/platform/audit-trail"), current("Enterprise Administration", "/why-mdarix")] },
  ],
  Solutions: [
    { title: "By Challenge", items: [current("Investigate Complaint Increases", "/solutions#complaints"), current("Understand Product Changes", "/solutions#changes"), current("Find Affected Products & Lots", "/solutions#affected"), current("Investigate Supplier Issues", "/solutions#supplier"), current("Connect Fragmented Evidence", "/solutions#evidence"), current("Challenge Suspected Root Causes", "/solutions#challenge"), current("Identify Missing Evidence", "/solutions#unknowns")] },
    { title: "By Role", items: [current("Quality Leaders", "/solutions#quality-leaders", "See the full investigation picture."), current("Investigators / QA", "/solutions#investigators", "Move from signal to evidence."), current("Regulatory Affairs", "/solutions#regulatory", "Prepare traceable review context."), current("Product / R&D", "/solutions#product", "Connect changes to outcomes."), current("Supplier Quality", "/solutions#supplier-quality", "Follow supplier and component relationships."), current("Manufacturing Quality", "/solutions#manufacturing", "Understand affected lots and changes."), current("Executives", "/solutions#executives", "Review decision-ready assurance.")] },
    { title: "By Investigation", items: [current("Complaint Investigation", "/solutions#complaint-investigation"), current("ProductVersion Investigation", "/solutions#version-investigation"), current("Change Investigation", "/solutions#change-investigation"), current("Supplier Investigation", "/solutions#supplier-investigation"), current("Component Investigation", "/solutions#component-investigation"), current("Lot / Batch Investigation", "/solutions#lot-investigation"), current("Risk & Failure Investigation", "/solutions#risk-investigation"), current("Cross-System Investigation", "/solutions#cross-system")] },
    { title: "Investigate with MDARIX", items: [current("Why did complaints increase after Rev D?", "/platform/investigation", "Follow a signal through product version, change, component, supplier, lots, evidence, hypotheses, unknowns, assurance, and human decision.")] },
  ],
  "Product Lifecycle": [
    { title: "Discover & Define", items: [future("Product Strategy", "strategy"), future("User / Clinical Need", "clinical-need"), future("Product Requirements", "requirements")] },
    { title: "Develop & Prove", items: [future("Design & Development", "design"), future("Design Controls", "design-controls"), future("Verification & Validation", "verification"), future("Clinical Intelligence", "clinical"), future("Regulatory Intelligence", "regulatory")] },
    { title: "Build & Release", items: [future("Manufacturing Intelligence", "manufacturing"), current("Supplier Intelligence", "/platform/reality-graph"), current("Component Intelligence", "/platform/product-360"), current("Lot / Batch Intelligence", "/platform/product-360"), current("Change Intelligence", "/platform/timeline")] },
    { title: "Monitor, Improve & Evolve", items: [current("Complaint Intelligence", "/solutions#complaints"), current("Post-Market Investigation", "/platform/investigation"), future("Signal Intelligence", "signal"), current("Evidence Intelligence", "/platform/evidence"), future("CAPA Intelligence", "capa"), future("Field Action / Recall Intelligence", "recall"), current("Product Change Intelligence", "/platform/timeline"), future("Continuous Monitoring", "monitoring"), future("Product Retirement", "retirement")] },
  ],
  "Why MDARIX": [
    { title: "A Different Intelligence Layer", items: [current("Not Another QMS", "/why-mdarix#not-qms", "Keep existing systems of record."), current("Product Reality", "/why-mdarix#product-reality", "Understand relationships across lifecycle information."), current("Investigation Intelligence", "/why-mdarix#investigation", "Investigate across connected context."), current("Evidence Before Inference", "/why-mdarix#evidence", "Separate facts, interpretations, hypotheses, and decisions.")] },
    { title: "Trustworthy Investigation", items: [current("Challenge the Explanation", "/why-mdarix#challenge"), current("AI You Can Inspect", "/why-mdarix#inspectable-ai"), current("Humans Decide", "/why-mdarix#humans-decide")] },
    { title: "Questions MDARIX Helps Explore", items: [current("What changed before the signal?", "/solutions#changes"), current("Which versions and lots are affected?", "/solutions#affected"), current("What evidence contradicts the cause?", "/solutions#challenge"), current("What information is still missing?", "/solutions#unknowns")] },
    { title: "Trust Foundations", items: [current("AI Assurance", "/platform/ai-assurance"), current("Security & Access", "/security"), current("Plans & Entitlements", "/plans"), current("Integration Approach", "/integrations")] },
  ],
};

const pages: Record<string, { eyebrow: string; title: string; copy: string }> = {
  "/": { eyebrow: "Product investigation intelligence for medical devices", title: "Understand what happened. Investigate why. Decide with evidence.", copy: "Connect product, quality, manufacturing, and post-market evidence to investigate device issues across the lifecycle." },
  "/platform": { eyebrow: "Platform & AI", title: "A connected intelligence layer for product investigation.", copy: "Reconstruct product reality, investigate competing explanations, expose contradictions and unknowns, and preserve traceable human decisions." },
  "/solutions": { eyebrow: "Solutions", title: "Start with the question your team needs to answer.", copy: "Investigate complaint increases, product changes, affected lots, supplier issues, fragmented evidence, suspected causes, and missing information across systems." },
  "/product-lifecycle": { eyebrow: "Product lifecycle", title: "Intelligence from product definition through post-market evolution.", copy: "Current investigation capabilities anchor a broader lifecycle vision. Future areas are identified clearly without implying working functionality." },
  "/why-mdarix": { eyebrow: "Why MDARIX", title: "Evidence before inference. Challenge before conclusion.", copy: "MDARIX works above your existing systems of record to reconstruct product reality and make investigation intelligence inspectable." },
  "/resources": { eyebrow: "Resources", title: "Explore product investigation intelligence.", copy: "Learn how MDARIX connects product reality, evidence, temporal context, investigation, decisions, assurance, and governance." },
  "/plans": { eyebrow: "Plans", title: "Start with Free Early Access.", copy: "Create an account, verify your email, and enter a tenant-scoped development workspace. Future commercial packaging is not represented here." },
  "/capabilities": { eyebrow: "Current capabilities", title: "From connected lifecycle data to traceable decisions.", copy: "Explore the current product reality, investigation, evidence, challenge, decision, assurance, and governance capabilities." },
  "/roadmap": { eyebrow: "Product roadmap", title: "Current capabilities and the broader lifecycle direction.", copy: "Future roadmap areas are informational and do not represent available workflows or committed release dates." },
  "/integrations": { eyebrow: "Integrations", title: "Work above the systems you already trust.", copy: "QMS, PLM, ERP, MES, supplier, document, and evidence platforms remain authoritative systems of record." },
  "/security": { eyebrow: "Security & access", title: "Controlled, tenant-scoped, and traceable by design.", copy: "Authentication, role and field authorization, action controls, provenance, and human authority form the current security foundation. Independent certification is not claimed." },
  "/ai-trust": { eyebrow: "AI trust", title: "Grounded intelligence with visible limits.", copy: "MDARIX preserves evidence references, temporal context, contradictions, unknowns, provenance, and human review. AI does not create the final regulated decision." },
  "/request-demo": { eyebrow: "Get started", title: "Explore MDARIX in your lifecycle context.", copy: "Create an account, verify your email, sign in, and enter the tenant-scoped application." },
};

const anchorPages: Record<string, { eyebrow: string; title: string; copy: string }> = {
  complaints: { eyebrow: "Solution · Complaint signals", title: "Find out what changed before complaints increased.", copy: "Connect complaint patterns to product versions, changes, components, suppliers, lots, and evidence so investigators can separate a signal from a conclusion." },
  changes: { eyebrow: "Solution · Product changes", title: "Understand the changes that shaped the signal.", copy: "Compare product revisions and controlled changes with complaint timing, affected lots, configuration, and supporting evidence." },
  affected: { eyebrow: "Solution · Affected products and lots", title: "Trace impact from version to lot.", copy: "Follow product versions, component relationships, suppliers, and lot context to identify what is affected and what remains unknown." },
  supplier: { eyebrow: "Solution · Supplier investigation", title: "Connect supplier context to product reality.", copy: "Bring supplier, component, change, lot, and complaint relationships into one investigation workspace." },
  evidence: { eyebrow: "Solution · Evidence intelligence", title: "Make evidence visible before inference.", copy: "Review source anchors, reliability, temporal context, contradictions, and missing evidence before forming a hypothesis." },
  challenge: { eyebrow: "Solution · AI Challenger", title: "Challenge the explanation before it becomes a conclusion.", copy: "Expose competing hypotheses, contradictions, unknowns, and limitations so authorized humans can review the reasoning." },
  unknowns: { eyebrow: "Solution · Unknowns radar", title: "See what the investigation still cannot establish.", copy: "Surface incomplete traceability, missing lot references, unsupported failure chains, and other evidence gaps." },
  "quality-leaders": { eyebrow: "Role · Quality leaders", title: "Give quality leaders the full investigation picture.", copy: "Review product reality, evidence quality, competing explanations, assurance, and human decisions in one governed view." },
  investigators: { eyebrow: "Role · Investigators / QA", title: "Move from signal to evidence with confidence.", copy: "Build a traceable investigation across product, change, supplier, lot, complaint, evidence, and hypothesis context." },
  regulatory: { eyebrow: "Role · Regulatory affairs", title: "Prepare traceable review context.", copy: "Preserve provenance, limitations, temporal context, and human review boundaries for regulated investigation workflows." },
  product: { eyebrow: "Role · Product and R&D", title: "Connect product changes to outcomes.", copy: "Understand how revisions, components, configuration, and lifecycle events relate to downstream signals." },
  "supplier-quality": { eyebrow: "Role · Supplier quality", title: "Follow supplier and component relationships.", copy: "Investigate supplier-linked signals with affected lots, component revisions, evidence, and missing context in view." },
  manufacturing: { eyebrow: "Role · Manufacturing quality", title: "Understand affected lots and changes.", copy: "Connect manufacturing context to product versions, lots, complaints, evidence, and investigation decisions." },
  executives: { eyebrow: "Role · Executives", title: "Review decision-ready assurance.", copy: "See what is known, what is challenged, what remains unresolved, and where human authorization is required." },
};

const pricingPlans = [
  { name: "Free", price: "$0", cadence: "forever", note: "Explore the connected investigation workspace.", features: ["1 workspace", "Up to 3 users", "Product 360 and investigation basics", "Community guidance"], action: "Start free" },
  { name: "Individual", price: "$49", cadence: "per user / month", note: "For focused quality and investigation work.", features: ["1 workspace", "Up to 10 users", "Evidence and hypothesis intelligence", "Standard support"], action: "Choose Individual" },
  { name: "Pro", price: "$149", cadence: "per user / month", note: "For teams connecting evidence across functions.", features: ["Unlimited workspaces", "Up to 50 users", "AI assurance and decision workflows", "Priority support"], action: "Choose Pro", featured: true },
  { name: "Enterprise", price: "Custom", cadence: "annual plan", note: "For governed, tenant-scoped deployment at scale.", features: ["Advanced administration", "SSO and enterprise access", "Custom integrations", "Dedicated success support"], action: "Talk to us" },
];

export function PublicMegaSite({ path }: { path: string }) {
  const [openMenu, setOpenMenu] = useState<string | null>(null); const [mobileOpen, setMobileOpen] = useState(false); const [hash, setHash] = useState(() => window.location.hash.slice(1));
  useEffect(() => { const close = (event: KeyboardEvent) => { if (event.key === "Escape") { setOpenMenu(null); setMobileOpen(false); } }; window.addEventListener("keydown", close); return () => window.removeEventListener("keydown", close); }, []);
  useEffect(() => { const update = () => setHash(window.location.hash.slice(1)); window.addEventListener("hashchange", update); return () => window.removeEventListener("hashchange", update); }, [path]);
  const capability = path.startsWith("/platform/") ? (path.split("/").pop() ?? "capability").replace(/-/g, " ").replace(/\b\w/g, letter => letter.toUpperCase()) : null;
  const roadmapTarget = path === "/roadmap" && window.location.hash ? window.location.hash.slice(1).replace(/-/g, " ").replace(/\b\w/g, letter => letter.toUpperCase()) : null;
  const anchorPage = anchorPages[hash];
  const page = roadmapTarget ? { eyebrow: "Future", title: roadmapTarget, copy: "Planned as part of the broader MDARIX Medical Device Product Lifecycle Intelligence platform. This page is informational and does not represent available functionality." } : anchorPage ?? (capability ? { eyebrow: "Current capability", title: capability, copy: `${capability} contributes to the connected MDARIX product-investigation workflow across product, version, temporal, evidence, tenant, and human-governance boundaries.` } : pages[path] ?? pages["/"]);
  const questionFlow = ["Complaint signal", "ProductVersion", "Change", "Component", "Supplier", "Affected lots", "Evidence", "Hypotheses", "Contradictions", "Unknowns", "Assurance", "Human decision"];
  const isHome = path === "/";
  if (typeof document !== "undefined") document.documentElement.dataset.publicPath = path;
  return <div className="public-shell" onClick={() => openMenu && setOpenMenu(null)}><header className="public-header" onClick={event => event.stopPropagation()}><a className="brand" href="/">MDARIX</a><button className="mobile-menu-button" aria-expanded={mobileOpen} aria-controls="public-navigation" onClick={() => setMobileOpen(!mobileOpen)}>Menu</button><nav id="public-navigation" className={mobileOpen ? "mobile-open" : ""}>{Object.keys(menus).map(name => <button key={name} aria-expanded={openMenu === name} onClick={() => setOpenMenu(openMenu === name ? null : name)}>{name}</button>)}<a href="/resources">Resources</a><a href="/plans">Plans</a></nav><div className="public-actions"><a href="/signin">Sign in</a><a className="primary-action" href="/signup">Get started</a></div>{openMenu && <div className="mega-menu" role="region" aria-label={`${openMenu} menu`}>{menus[openMenu].map(group => <section key={group.title}><h2>{group.title}</h2>{group.items.map(entry => <a key={entry.label} href={entry.href}><span><strong>{entry.label}</strong>{entry.description && <em>{entry.description}</em>}</span>{entry.future && <small className="status-future">Future</small>}</a>)}</section>)}</div>}</header>
    <main className="public-main"><section className="public-hero"><span className="eyebrow">{page.eyebrow}</span><h1>{page.title}</h1><p>{page.copy}</p><div className="public-cta"><a className="primary-action" href="/platform">Explore the platform</a><a className="secondary-link" href="/signup">Get started →</a></div></section>
      <section className="public-question"><span className="eyebrow">A product investigation question</span><h2>Why did shutdown complaints increase after Product Rev D?</h2><p>MDARIX helps teams follow the question across product reality, evidence, uncertainty, assurance, and controlled human decision-making.</p><div className="question-flow">{questionFlow.map((step, index) => <React.Fragment key={step}><article>{step}</article>{index < questionFlow.length - 1 && <ChevronRight aria-hidden="true" />}</React.Fragment>)}</div></section>
      <section className="public-story"><div><span className="eyebrow">A different intelligence layer</span><h2>Keep your systems of record. Connect the investigation.</h2></div><div className="story-grid"><article><strong>Product reality</strong><p>Relate products, versions, components, suppliers, lots, changes, complaints, risks, and evidence.</p></article><article><strong>Evidence before inference</strong><p>Separate observations, interpretations, hypotheses, contradictions, unknowns, and decisions.</p></article><article><strong>AI you can inspect</strong><p>Show grounding, temporal context, ProductVersion validation, provenance, and limitations.</p></article><article><strong>Humans decide</strong><p>AI supports investigation. Authorized humans make controlled decisions.</p></article></div></section>
      {path === "/roadmap" && !roadmapTarget && <section className="public-story roadmap-grid"><article><h2>Current capabilities</h2><p>Product 360, Reality Graph, temporal context, evidence intelligence, investigation, hypotheses, challenger, unknowns, failure chain, counterfactuals, decisions, assurance, and governance foundations.</p></article><article><span className="status-future">Future</span><h2>Broader lifecycle intelligence</h2><p>Strategy, requirements, design controls, regulatory, clinical, manufacturing operations, CAPA, recall, continuous monitoring, and retirement remain roadmap areas.</p></article></section>}
      {path === "/plans" && <section className="pricing-section"><p className="pricing-disclaimer">Illustrative early-access pricing. Plans and billing are not yet enabled.</p><div className="pricing-grid">{pricingPlans.map(plan => <article className={`pricing-card ${plan.featured ? "pricing-card-featured" : ""}`} key={plan.name}>{plan.featured && <span className="pricing-badge">Most popular</span>}<h2>{plan.name}</h2><p>{plan.note}</p><div className="pricing-price">{plan.price}</div><small>{plan.cadence}</small><ul>{plan.features.map(feature => <li key={feature}>{feature}</li>)}</ul><a className={plan.featured ? "primary-action" : "secondary-action"} href={plan.name === "Enterprise" ? "/request-demo" : "/signup"}>{plan.action}</a></article>)}</div></section>}
    </main><footer className="public-footer"><span>MDARIX — System of Intelligence, not System of Record.</span><span><a href="/capabilities">Capabilities</a> · <a href="/roadmap">Roadmap</a> · <a href="/security">Security</a></span></footer></div>;
}
