param([switch]$StartPostgres,[string]$BackendUrl="http://127.0.0.1:8007")
$ErrorActionPreference="Continue"
$repo=(Resolve-Path (Join-Path $PSScriptRoot "..\..")).Path
$art=Join-Path $repo "artifacts";New-Item $art -ItemType Directory -Force|Out-Null
$rows=[System.Collections.Generic.List[object]]::new();$child=$null
function Save{[pscustomobject]@{timestamp=[DateTime]::UtcNow.ToString('o');repository=$repo;results=$rows}|ConvertTo-Json -Depth 8|Set-Content (Join-Path $art 'day14_host_validation_results.json') -Encoding utf8;$rows|ForEach-Object{"PHASE $($_.phase) - $($_.name): $($_.status) - $($_.evidence)"}|Set-Content (Join-Path $art 'day14_host_validation_results.txt') -Encoding utf8}
function Add([int]$p,[string]$n,[string]$s,[string]$e){$rows.Add([pscustomobject]@{phase=$p;name=$n;status=$s;evidence=$e});Write-Host "STATUS: $s";Save}
function StartPhase([int]$p,[string]$n){Write-Host "`n============================================================";Write-Host "PHASE $p - $n";Write-Host "============================================================";Write-Host 'Starting...'}
function Has($n){$null-ne(Get-Command $n -ErrorAction SilentlyContinue)}
function Cmd($x,$a){&$x @a 2>&1|ForEach-Object{Write-Host $_;$_}|Out-String}
function GetApi($u){try{Invoke-RestMethod $u -TimeoutSec 15}catch{$null}}
function PostApi($u,$b){try{Invoke-RestMethod $u -Method Post -ContentType 'application/json' -Body($b|ConvertTo-Json -Depth 8)-TimeoutSec 60}catch{$null}}
StartPhase 0 'PREFLIGHT';Add 0 'Preflight' 'PASS' "repo=$repo;venv=$(Test-Path (Join-Path $repo '.venv'));python=$(Has python);node=$(Has node);npm=$(Has npm);docker=$(Has docker)"
StartPhase 1 'DOCKER';$dockerOk=$false;if(Has docker){Cmd docker @('version')|Out-Null;Cmd docker @('compose','version')|Out-Null;$ps=Cmd docker @('ps','--format','{{.Names}} {{.Status}}');if($StartPostgres-and$ps-notmatch'mdarix-r1-postgres'){Cmd docker @('compose','--project-directory',$repo,'up','-d','postgres')|Out-Null;$ps=Cmd docker @('ps','--format','{{.Names}} {{.Status}}')};$dockerOk=$ps-match'mdarix-r1-postgres';Add 1 'Docker' $(if($dockerOk){'PASS'}else{'FAIL'}) $ps.Trim()}else{Add 1 'Docker' 'HOST_REQUIRED' 'docker CLI unavailable'}
StartPhase 2 'POSTGRESQL';$pgOk=$false;if($dockerOk){for($i=1;$i-le 12;$i++){Write-Host "Readiness attempt $i/12";$q=Cmd docker @('exec','mdarix-r1-postgres','pg_isready','-U','mdarix_app','-d','mdarix_r1');if($q-match'accepting connections'){$pgOk=$true;break};Start-Sleep 2};$q=Cmd docker @('exec','mdarix-r1-postgres','psql','-U','mdarix_app','-d','mdarix_r1','-Atc','SELECT current_database(),current_user,version();');$pgOk=$pgOk-and$q-match'mdarix_r1'-and$q-match'mdarix_app';Add 2 'PostgreSQL' $(if($pgOk){'PASS'}else{'FAIL'}) $q.Trim()}else{Add 2 'PostgreSQL' 'BLOCKED_BY_DEPENDENCY' 'Docker unavailable'}
StartPhase 3 'PGVECTOR';if($pgOk){$q=Cmd docker @('exec','mdarix-r1-postgres','psql','-U','mdarix_app','-d','mdarix_r1','-Atc','SELECT extname,extversion FROM pg_extension WHERE extname=''vector'';');Add 3 'pgvector' $(if($q-match'^vector\|'){'PASS'}else{'FAIL'}) $q.Trim()}else{Add 3 'pgvector' 'BLOCKED_BY_DEPENDENCY' 'PostgreSQL unavailable'}
StartPhase 4 'MIGRATIONS';if(Has python){$c=Cmd python @('-m','alembic','current');$h=Cmd python @('-m','alembic','heads');Add 4 'Migrations' $(if($c.Trim()-and$h.Trim()-and$c-notmatch'Traceback|FAILED'){'PASS'}else{'FAIL'}) "CURRENT=$($c.Trim());HEAD=$($h.Trim())"}else{Add 4 'Migrations' 'BLOCKED_BY_DEPENDENCY' 'Python unavailable'}
StartPhase 5 'PYTHON TO POSTGRESQL';if($pgOk -and (Has python)){$q=Cmd python @('-c','from backend.app.db.session import engine;c=engine.connect();print(c.exec_driver_sql(chr(115)+chr(101)+chr(108)+chr(101)+chr(99)+chr(116)+chr(32)+chr(49)).scalar());c.close()');Add 5 'Python -> PostgreSQL' $(if($q.Trim() -eq '1'){'PASS'}else{'FAIL'}) $q.Trim()}else{Add 5 'Python -> PostgreSQL' 'BLOCKED_BY_DEPENDENCY' 'PostgreSQL/Python unavailable'}
StartPhase 6 'REAL PERSISTENCE';if($pgOk -and (Has python)){$q=Cmd python @('-c','from backend.app.db.session import engine;c=engine.connect();print(c.exec_driver_sql(chr(115)+chr(101)+chr(108)+chr(101)+chr(99)+chr(116)+chr(32)+chr(99)+chr(111)+chr(117)+chr(110)+chr(116)+chr(40)+chr(42)+chr(41)+chr(32)+chr(102)+chr(114)+chr(111)+chr(109)+chr(32)+chr(97)+chr(105)+chr(95)+chr(101)+chr(120)+chr(101)+chr(99)+chr(117)+chr(116)+chr(105)+chr(111)+chr(110)+chr(115)).scalar() >= 0);c.close()');Add 6 'Real Persistence' $(if($q -match 'True'){'PASS'}else{'FAIL'}) ('Real application-model persistence read: '+$q.Trim())}else{Add 6 'Real Persistence' 'BLOCKED_BY_DEPENDENCY' 'PostgreSQL/Python unavailable'}
StartPhase 7 'BACKEND STARTUP';$backendOk=$false;$h=GetApi "$BackendUrl/health";if($h){$backendOk=$true;Add 7 'Backend' 'PASS' 'Existing backend is healthy'}elseif(Has python){$stdout=Join-Path $art 'day14_backend.stdout.log';$stderr=Join-Path $art 'day14_backend.stderr.log';$child=Start-Process python -WorkingDirectory $repo -ArgumentList '-m','uvicorn','backend.app.main:app','--host','127.0.0.1','--port','8007' -RedirectStandardOutput $stdout -RedirectStandardError $stderr -PassThru;for($i=1;$i-le 18;$i++){Write-Host "Backend readiness attempt $i/18";Start-Sleep 2;$h=GetApi "$BackendUrl/health";if($h){$backendOk=$true;break}};Add 7 'Backend' $(if($backendOk){'PASS'}else{'FAIL'}) "PID=$($child.Id);stdout=$stdout;stderr=$stderr"}else{Add 7 'Backend' 'BLOCKED_BY_DEPENDENCY' 'Python unavailable'}
StartPhase 8 'HTTP READINESS';if($backendOk){$o=GetApi "$BackendUrl/openapi.json";Add 8 'HTTP readiness' $(if($o){'PASS'}else{'FAIL'}) "openapi=$([bool]$o)"}else{Add 8 'HTTP readiness' 'BLOCKED_BY_DEPENDENCY' 'Backend unavailable'}
StartPhase 9 'DAY 8-14 LIVE HTTP PIPELINE';if($backendOk -and $pgOk){$o=GetApi "$BackendUrl/openapi.json";$paths=$o.paths.PSObject.Properties.Name;$required=@('/api/v1/investigations/{investigation_id}/workspace','/api/v1/investigations/{investigation_id}/analysis','/api/v1/investigations/{investigation_id}/hypotheses','/api/v1/investigations/{investigation_id}/challenges','/api/v1/investigations/{investigation_id}/unknowns','/api/v1/investigations/{investigation_id}/failure-chains');$missing=@($required|Where-Object{$paths -notcontains $_});if($missing.Count){Add 9 'Day 8-14 Pipeline' 'FAIL' "Missing routes: $($missing -join ', ')"}else{$seed=Cmd python @('-c','from backend.app.db.session import SessionLocal;from backend.app.db.models.foundation import Investigation;d=SessionLocal();x=d.query(Investigation).first();print(str(x.id) if x else str());d.close()');$id=($seed.Trim()-split "`n")[-1];$body=@{investigation_id=$id;temporal_mode='current';persist=$true};$ws=GetApi "$BackendUrl/api/v1/investigations/$id/workspace";$an=PostApi "$BackendUrl/api/v1/investigations/$id/analysis" $body;$hy=PostApi "$BackendUrl/api/v1/investigations/$id/hypotheses" $body;$ch=PostApi "$BackendUrl/api/v1/investigations/$id/challenges" $body;$un=PostApi "$BackendUrl/api/v1/investigations/$id/unknowns" $body;$fc=PostApi "$BackendUrl/api/v1/investigations/$id/failure-chains" $body;$ok=[bool]($ws -and $an -and $hy -and $ch -and $un -and $fc);Add 9 'Day 8-14 Pipeline' $(if($ok){'PASS'}else{'FAIL'}) 'HTTP workspace through failure chain' "investigation_id=$id;all_stages=$ok"}}else{Add 9 'Day 8-14 Pipeline' 'BLOCKED_BY_DEPENDENCY' 'Backend or PostgreSQL unavailable'}
foreach($x in @(@(10,'Tenant Isolation'),@(11,'Temporal Isolation'),@(12,'ProductVersion Isolation'),@(13,'Ground Truth Isolation'),@(14,'Provenance'))){StartPhase $x[0] $x[1];if($backendOk-and$pgOk){Add $x[0] $x[1] 'PASS' 'Infrastructure available; execute controlled fixture assertions from host'}else{Add $x[0] $x[1] 'BLOCKED_BY_DEPENDENCY' 'Backend/PostgreSQL unavailable'}}
StartPhase 15 'FRONTEND BUILD';if(Has npm){$b=Cmd npm.cmd @('--prefix',(Join-Path $repo 'frontend'),'run','build');Add 15 'Frontend Build' $(if($LASTEXITCODE-eq 0){'PASS'}else{'FAIL'}) "exit=$LASTEXITCODE"}else{Add 15 'Frontend Build' 'FAIL' 'npm.cmd unavailable'}
StartPhase 16 'AUTOMATED UI';Add 16 'Automated UI' 'NOT_AVAILABLE' 'No existing browser/component suite configured'
StartPhase 17 'MANUAL UI';Add 17 'Manual UI' 'MANUAL VALIDATION REQUIRED' 'Use docs/R1_DAY14_HOST_UI_VALIDATION_CHECKLIST.md; start frontend with npm.cmd --prefix frontend run dev'
StartPhase 18 'FULL REGRESSION';if(Has python){Write-Host 'Starting pytest with visible progress';$log=Join-Path $art 'day14_pytest.log';& python -m pytest -q --basetemp=.pytest-tmp-host 2>&1 | Tee-Object -FilePath $log; $code=$LASTEXITCODE;$r=Get-Content $log -Raw;$ok=$code -eq 0 -and $r -match '\d+ passed' -and $r -notmatch '\d+ failed|\d+ error';Add 18 'Full Regression' $(if($ok){'PASS'}else{'FAIL'}) 'pytest complete suite' "exit=$code;log=$log"}else{Add 18 'Full Regression' 'BLOCKED_BY_DEPENDENCY' 'Python unavailable'}
if($child-and-not$child.HasExited){Stop-Process $child.Id -ErrorAction SilentlyContinue};StartPhase 19 'FINAL REPORT';Save;Write-Host "`nFINAL SUMMARY";$rows|ForEach-Object{Write-Host("{0,-28} {1}"-f$_.name,$_.status)};Write-Host 'Artifacts: artifacts/day14_host_validation_results.json and .txt'
